/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ServiceCenter;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Font;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Shehan Atapattu
 */
public class CshrReport extends javax.swing.JFrame {

    /**
     * Creates new form CshrReport
     */
    public CshrReport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        dateChooserCombo5 = new datechooser.beans.DateChooserCombo();
        dateChooserCombo6 = new datechooser.beans.DateChooserCombo();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel29 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1205, 843));
        setPreferredSize(new java.awt.Dimension(1200, 800));

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jPanel2.setLayout(null);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3)));
        jPanel9.setLayout(null);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Get Sales");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton2);
        jButton2.setBounds(700, 80, 115, 42);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Select Time Period");
        jPanel9.add(jLabel18);
        jLabel18.setBounds(15, 16, 135, 24);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("To");
        jPanel9.add(jLabel19);
        jLabel19.setBounds(230, 60, 18, 20);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("From");
        jPanel9.add(jLabel20);
        jLabel20.setBounds(15, 59, 36, 17);
        jPanel9.add(dateChooserCombo5);
        dateChooserCombo5.setBounds(63, 57, 130, 22);
        jPanel9.add(dateChooserCombo6);
        dateChooserCombo6.setBounds(260, 60, 120, 22);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Stock Items", "Date" }));
        jPanel9.add(jComboBox2);
        jComboBox2.setBounds(520, 50, 110, 30);

        jLabel29.setForeground(new java.awt.Color(240, 240, 240));
        jLabel29.setText("Report By:");
        jPanel9.add(jLabel29);
        jLabel29.setBounds(450, 50, 60, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sariya1200.jpg"))); // NOI18N
        jPanel9.add(jLabel7);
        jLabel7.setBounds(-60, 0, 910, 140);

        jPanel2.add(jPanel9);
        jPanel9.setBounds(160, 160, 810, 130);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ItemNo", "ItemName", "Sales", "Revenue"
            }
        ));
        jScrollPane2.setViewportView(jTable3);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(20, 350, 570, 230);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Report");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(880, 690, 93, 47);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("Home");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(120, 690, 85, 47);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("Exit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(260, 690, 67, 47);

        jLabel28.setForeground(new java.awt.Color(240, 240, 240));
        jLabel28.setText("Total:");
        jPanel2.add(jLabel28);
        jLabel28.setBounds(820, 620, 34, 30);

        jTextField7.setEditable(false);
        jPanel2.add(jTextField7);
        jTextField7.setBounds(870, 620, 170, 30);

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ItemNo", "ItemName", "Sales", "Revenue"
            }
        ));
        jScrollPane4.setViewportView(jTable6);

        jPanel2.add(jScrollPane4);
        jScrollPane4.setBounds(640, 350, 530, 230);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sariya1200.jpg"))); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(0, 0, 1200, 800);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ServiceCenter/saman.png"))); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(120, 80, 810, 130);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sariya1200.jpg"))); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(40, 110, 1210, 440);

        jTabbedPane1.addTab("Sales", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1196, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 833, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        DashBoard dbd=new DashBoard();
        dbd.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
        String today = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(Calendar.getInstance().getTime());
        JFileChooser dialog = new JFileChooser();
        dialog.setSelectedFile(new File("sales report by.pdf"));
        int dialogResult = dialog.showSaveDialog(null);
        if (dialogResult == JFileChooser.APPROVE_OPTION) {
            String filePath = dialog.getSelectedFile().getPath();

            try {

                Document myDocument = new Document();

                PdfWriter myWriter = PdfWriter.getInstance(myDocument, new FileOutputStream(filePath));
                myDocument.open();
                myWriter.setPageEvent(new MyPdfPageEventHelper("saman.png"));
                myDocument.add(new Paragraph("\n\n\n\n\n\n\n\n\n"));

                myDocument.add(new Paragraph("", FontFactory.getFont(FontFactory.TIMES_BOLD, 20, Font.BOLD)));
                myDocument.add(new Paragraph("", FontFactory.getFont(FontFactory.TIMES_BOLD, 15, Font.PLAIN)));
                myDocument.add(new Paragraph("", FontFactory.getFont(FontFactory.TIMES_BOLD, 15, Font.PLAIN)));

                Paragraph ph = new Paragraph("SALES\n", FontFactory.getFont(FontFactory.TIMES_BOLD, 20, Font.BOLD));
                ph.setAlignment(Paragraph.ALIGN_CENTER);
                myDocument.add(ph);

                myDocument.add(new Paragraph("\n\n"));

                String from = new SimpleDateFormat("dd-MM-yyyy").format(dateChooserCombo5.getSelectedDate().getTime());
                String to = new SimpleDateFormat("dd-MM-yyyy").format(dateChooserCombo6.getSelectedDate().getTime());

                PdfPTable table3 = new PdfPTable(2);
                table3.setWidthPercentage(100);
                float[] columnWidths3 = new float[]{12, 4};
                table3.setWidths(columnWidths3);

                PdfPCell cell1 = new PdfPCell(new Paragraph("from: " + from, FontFactory.getFont(FontFactory.TIMES, 12)));

                PdfPCell cell2 = new PdfPCell(new Paragraph("To: " + to, FontFactory.getFont(FontFactory.TIMES, 12)));
                cell2.setHorizontalAlignment(Element.ALIGN_LEFT);
                cell1.setBorderColor(BaseColor.WHITE);
                cell2.setBorderColor(BaseColor.WHITE);

                table3.addCell(cell1);
                table3.addCell(cell2);

                myDocument.add(table3);
                myDocument.add(new Paragraph("\n\n"));

                if (jComboBox2.getSelectedItem().toString().equals("Stock Items")) {
                    PdfPTable table = new PdfPTable(7);

                    table.setWidthPercentage(100);
                    float[] columnWidths = new float[]{5, 5, 5, 5, 5, 5, 5};
                    table.setWidths(columnWidths);

                    //myDocument.add(new Paragraph(new Date().toString()));
                    //myDocument.add(new Paragraph("--------------------------------------------------------------------------------------------------------------------------------"));
                    table.addCell(new PdfPCell(new Paragraph("Item Name", FontFactory.getFont(FontFactory.TIMES_ROMAN, 9, Font.BOLD))));
                    table.addCell(new PdfPCell(new Paragraph("Brand", FontFactory.getFont(FontFactory.TIMES_ROMAN, 9, Font.BOLD))));
                    table.addCell(new PdfPCell(new Paragraph("Model", FontFactory.getFont(FontFactory.TIMES_ROMAN, 9, Font.BOLD))));
                    table.addCell(new PdfPCell(new Paragraph("Qty", FontFactory.getFont(FontFactory.TIMES_ROMAN, 9, Font.BOLD))));
                    table.addCell(new PdfPCell(new Paragraph("Unit Price", FontFactory.getFont(FontFactory.TIMES_ROMAN, 9, Font.BOLD))));
                    table.addCell(new PdfPCell(new Paragraph("Discount", FontFactory.getFont(FontFactory.TIMES_ROMAN, 9, Font.BOLD))));
                    table.addCell(new PdfPCell(new Paragraph("Total", FontFactory.getFont(FontFactory.TIMES_ROMAN, 9, Font.BOLD))));

                    for (int i = 0; i < jTable3.getRowCount(); i++) {

                        table.addCell(new PdfPCell(new Paragraph(jTable3.getValueAt(i, 0).toString(), FontFactory.getFont(FontFactory.TIMES_ROMAN, 8, Font.PLAIN))));
                        table.addCell(new PdfPCell(new Paragraph(jTable3.getValueAt(i, 1).toString(), FontFactory.getFont(FontFactory.TIMES_ROMAN, 8, Font.PLAIN))));
                        table.addCell(new PdfPCell(new Paragraph(jTable3.getValueAt(i, 2).toString(), FontFactory.getFont(FontFactory.TIMES_ROMAN, 8, Font.PLAIN))));
                        table.addCell(new PdfPCell(new Paragraph(jTable3.getValueAt(i, 3).toString(), FontFactory.getFont(FontFactory.TIMES_ROMAN, 8, Font.PLAIN))));
                        table.addCell(new PdfPCell(new Paragraph(jTable3.getValueAt(i, 4).toString(), FontFactory.getFont(FontFactory.TIMES_ROMAN, 8, Font.PLAIN))));
                        table.addCell(new PdfPCell(new Paragraph(jTable3.getValueAt(i, 5).toString(), FontFactory.getFont(FontFactory.TIMES_ROMAN, 8, Font.PLAIN))));
                        table.addCell(new PdfPCell(new Paragraph(jTable3.getValueAt(i, 6).toString(), FontFactory.getFont(FontFactory.TIMES_ROMAN, 8, Font.PLAIN))));

                    }

                    myDocument.add(table);
                    myDocument.add(new Paragraph("\n"));
                    Paragraph pp = new Paragraph("Total sales:Rs " + jTextField7.getText() + "", FontFactory.getFont(FontFactory.TIMES, 12));
                    pp.setAlignment(Element.ALIGN_RIGHT);
                    myDocument.add(pp);
                    myDocument.add(new Paragraph("\n\n\n"));
                    myDocument.add(new Paragraph("--------------------------------------------------------------------------------------------------------------------------------"));

                    myDocument.close();

                } else {
                    PdfPTable table = new PdfPTable(8);

                    table.setWidthPercentage(100);
                    float[] columnWidths = new float[]{5, 5, 5, 5, 5, 5, 5, 5};
                    table.setWidths(columnWidths);

                    // myDocument.add(new Paragraph(new Date().toString()));
                    // myDocument.add(new Paragraph("--------------------------------------------------------------------------------------------------------------------------------"));
                    table.addCell(new PdfPCell(new Paragraph("Date", FontFactory.getFont(FontFactory.TIMES_ROMAN, 9, Font.BOLD))));
                    table.addCell(new PdfPCell(new Paragraph("Item Name", FontFactory.getFont(FontFactory.TIMES_ROMAN, 9, Font.BOLD))));
                    table.addCell(new PdfPCell(new Paragraph("Brand", FontFactory.getFont(FontFactory.TIMES_ROMAN, 9, Font.BOLD))));
                    table.addCell(new PdfPCell(new Paragraph("Model", FontFactory.getFont(FontFactory.TIMES_ROMAN, 9, Font.BOLD))));
                    table.addCell(new PdfPCell(new Paragraph("Qty", FontFactory.getFont(FontFactory.TIMES_ROMAN, 9, Font.BOLD))));
                    table.addCell(new PdfPCell(new Paragraph("Unit Price", FontFactory.getFont(FontFactory.TIMES_ROMAN, 9, Font.BOLD))));
                    table.addCell(new PdfPCell(new Paragraph("Discount", FontFactory.getFont(FontFactory.TIMES_ROMAN, 9, Font.BOLD))));
                    table.addCell(new PdfPCell(new Paragraph("Total", FontFactory.getFont(FontFactory.TIMES_ROMAN, 9, Font.BOLD))));

                    for (int i = 0; i < jTable3.getRowCount(); i++) {

                        table.addCell(new PdfPCell(new Paragraph(jTable3.getValueAt(i, 0).toString(), FontFactory.getFont(FontFactory.TIMES_ROMAN, 8, Font.PLAIN))));
                        table.addCell(new PdfPCell(new Paragraph(jTable3.getValueAt(i, 1).toString(), FontFactory.getFont(FontFactory.TIMES_ROMAN, 8, Font.PLAIN))));
                        table.addCell(new PdfPCell(new Paragraph(jTable3.getValueAt(i, 2).toString(), FontFactory.getFont(FontFactory.TIMES_ROMAN, 8, Font.PLAIN))));
                        table.addCell(new PdfPCell(new Paragraph(jTable3.getValueAt(i, 3).toString(), FontFactory.getFont(FontFactory.TIMES_ROMAN, 8, Font.PLAIN))));
                        table.addCell(new PdfPCell(new Paragraph(jTable3.getValueAt(i, 4).toString(), FontFactory.getFont(FontFactory.TIMES_ROMAN, 8, Font.PLAIN))));
                        table.addCell(new PdfPCell(new Paragraph(jTable3.getValueAt(i, 5).toString(), FontFactory.getFont(FontFactory.TIMES_ROMAN, 8, Font.PLAIN))));
                        table.addCell(new PdfPCell(new Paragraph(jTable3.getValueAt(i, 6).toString(), FontFactory.getFont(FontFactory.TIMES_ROMAN, 8, Font.PLAIN))));
                        table.addCell(new PdfPCell(new Paragraph(jTable3.getValueAt(i, 7).toString(), FontFactory.getFont(FontFactory.TIMES_ROMAN, 8, Font.PLAIN))));
                        //  table.addCell(new PdfPCell(new Paragraph(jTable3.getValueAt(i, 8).toString(), FontFactory.getFont(FontFactory.TIMES_ROMAN, 8, Font.PLAIN))));

                    }

                    myDocument.add(table);
                    myDocument.add(new Paragraph("\n"));
                    Paragraph pp = new Paragraph("Total sales: " + jTextField7.getText() + "", FontFactory.getFont(FontFactory.TIMES, 12));
                    pp.setAlignment(Element.ALIGN_RIGHT);
                    myDocument.add(pp);
                    myDocument.add(new Paragraph("\n\n\n"));
                    myDocument.add(new Paragraph("--------------------------------------------------------------------------------------------------------------------------------"));

                    myDocument.close();

                }

                JOptionPane.showMessageDialog(null, "Report was successfully generated");

            } catch (DocumentException ex) {
                Logger.getLogger(Allreports.class.getName()).log(Level.SEVERE, null, ex);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Allreports.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        view v = new view();
        String dt1 = new SimpleDateFormat("yyyy-MM-dd").format(dateChooserCombo5.getSelectedDate().getTime());
        String dt2 = new SimpleDateFormat("yyyy-MM-dd").format(dateChooserCombo6.getSelectedDate().getTime());
        if (jComboBox2.getSelectedItem().toString().equals("Stock Items")) {
            ResultSet rs1 = v.getTable("SELECT item.ItemName,item.Brand,item.Model, SUM(sell.Qty) as Qty, sell.unitprice,sell.discount,SUM(sell.Qty*(sell.unitprice-sell.discount)) AS total FROM `sell` INNER JOIN sales ON sell.InvoiceNo=sales.InvoiceNo INNER JOIN item ON item.ItemID=sell.ItemID WHERE sales.date BETWEEN '" + dt1 + "' AND '" + dt2 + "' GROUP BY sell.ItemID");
            ResultSet rs3 = v.getTable("SELECT item.ItemName,item.Brand,item.Model, SUM(include.Qty) as Qty, item.Price,SUM(include.Qty*(item.Price)) AS total FROM `include` INNER JOIN serviceinvoice ON include.InvoiceNo=serviceinvoice.InvoiceNo INNER JOIN item ON item.ItemID=include.ItemID WHERE serviceinvoice.date BETWEEN '" + dt1 + "' AND '" + dt2 + "' GROUP BY include.ItemID");
            jTable6.setModel(DbUtils.resultSetToTableModel(rs3));
            jTable6.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
            jTable3.setModel(DbUtils.resultSetToTableModel(rs1));
            jTable3.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
            double total = 0.0;
            for (int i = 0; i < jTable3.getRowCount(); i++) {
                total = total + Double.valueOf(jTable3.getModel().getValueAt(i, 6).toString());
            }
            for (int i = 0; i < jTable6.getRowCount(); i++) {
                total = total + Double.valueOf(jTable6.getModel().getValueAt(i, 5).toString());
            }
            jTextField7.setText(String.valueOf(total));
        } else {

            ResultSet rs2 = v.getTable("SELECT sales.date,item.ItemName,item.Brand,item.Model, SUM(sell.Qty) as Qty, sell.unitprice,sell.discount,SUM(sell.Qty*(sell.unitprice-sell.discount)) AS total FROM `sell` INNER JOIN sales ON sell.InvoiceNo=sales.InvoiceNo INNER JOIN item ON item.ItemID=sell.ItemID WHERE sales.date BETWEEN '" + dt1 + "' AND '" + dt2 + "' GROUP BY sales.date");
            ResultSet rs3 = v.getTable("SELECT serviceinvoice.date,item.ItemName,item.Brand,item.Model, SUM(include.Qty) as Qty, item.Price,SUM(include.Qty*(item.Price)) AS total FROM `include` INNER JOIN serviceinvoice ON include.InvoiceNo=serviceinvoice.InvoiceNo INNER JOIN item ON item.ItemID=include.ItemID WHERE serviceinvoice.date BETWEEN '" + dt1 + "' AND '" + dt2 + "' GROUP BY serviceinvoice.Date");
            jTable6.setModel(DbUtils.resultSetToTableModel(rs3));
            jTable6.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
            jTable3.setModel(DbUtils.resultSetToTableModel(rs2));
            jTable3.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
            double total = 0.0;
            for (int i = 0; i < jTable3.getRowCount(); i++) {
                total = total + Double.valueOf(jTable3.getModel().getValueAt(i, 7).toString());
            }
            for (int i = 0; i < jTable6.getRowCount(); i++) {
                total = total + Double.valueOf(jTable6.getModel().getValueAt(i, 6).toString());
            }
            jTextField7.setText(String.valueOf(total));
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CshrReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CshrReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CshrReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CshrReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CshrReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo dateChooserCombo5;
    private datechooser.beans.DateChooserCombo dateChooserCombo6;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
