/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ServiceCenter;

import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Shehan Atapattu
 */
public class customerReg extends javax.swing.JFrame {

    /**
     * Creates new form customerReg
     */
    public customerReg() {
        initComponents();
        loadCombo();
         try {
            ResultSet rs = v.getTable("select distinct(VehicleType) from service");
            uveh.removeAllItems();
            
            while (rs.next()) {
                uveh.addItem(rs.getString(1));
               
            }
        } catch (SQLException ex) {
            Logger.getLogger(customerReg.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
 private void loadCombo() {
        try {
            ResultSet rs = v.getTable("select (count(ServiceID)+1) from service");
            rs.next();
            sid.setText(rs.getString(1));
        } catch (SQLException ex) {
            Logger.getLogger(customerReg.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            ResultSet rs = v.getTable("select distinct(ServiceType) from service");
            uservice.removeAllItems();
            
            while (rs.next()) {
                uservice.addItem(rs.getString(1));
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(customerReg.class.getName()).log(Level.SEVERE, null, ex);
        }


    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cus = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        no = new javax.swing.JTextField();
        tel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        brand = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        vtype = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        telnew = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        veNonew = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cusnm = new javax.swing.JTextField();
        bnew = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        vnmnew = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        typenew = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        sid = new javax.swing.JTextField();
        ser = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        veh = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        fs = new javax.swing.JComboBox<String>();
        up = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        uservice = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        ufs = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        uup = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        uveh = new javax.swing.JComboBox<String>();
        usid = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1205, 843));

        jTabbedPane1.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N

        jPanel2.setLayout(null);

        jPanel1.setMinimumSize(new java.awt.Dimension(1200, 800));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 800));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Customer Name :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(240, 230, 150, 50);

        cus.setEditable(false);
        cus.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        cus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusActionPerformed(evt);
            }
        });
        jPanel1.add(cus);
        cus.setBounds(400, 240, 240, 40);

        jButton1.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(710, 160, 90, 50);

        no.setEditable(false);
        no.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noActionPerformed(evt);
            }
        });
        jPanel1.add(no);
        no.setBounds(400, 310, 240, 40);

        tel.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jPanel1.add(tel);
        tel.setBounds(400, 170, 240, 40);

        jLabel3.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Vehicle No :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(280, 300, 140, 50);

        jLabel5.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Telephone No :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(260, 170, 140, 40);

        jLabel8.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Vehicle Brand :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(260, 380, 130, 40);

        brand.setEditable(false);
        brand.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jPanel1.add(brand);
        brand.setBounds(400, 380, 240, 40);

        jLabel9.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Vehicle Name :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(260, 450, 130, 40);

        name.setEditable(false);
        name.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jPanel1.add(name);
        name.setBounds(400, 450, 240, 40);

        jButton2.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(640, 640, 120, 50);

        jButton3.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jButton3.setText("Next");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(810, 640, 120, 50);

        jButton6.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jButton6.setText("Home");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(150, 650, 110, 50);

        jLabel13.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(240, 240, 240));
        jLabel13.setText("Vehicle Type :");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(270, 510, 120, 50);

        vtype.setEditable(false);
        vtype.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jPanel1.add(vtype);
        vtype.setBounds(400, 520, 240, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sariya1200.jpg"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 1200, 810);

        jPanel2.add(jPanel1);
        jPanel1.setBounds(-2, -1, 1240, 810);

        jTabbedPane1.addTab("Search Customer", jPanel2);

        jPanel3.setLayout(null);

        jPanel4.setLayout(null);

        telnew.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        telnew.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                telnewKeyPressed(evt);
            }
        });
        jPanel4.add(telnew);
        telnew.setBounds(540, 220, 230, 40);

        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Customer Name   :");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(370, 150, 180, 40);

        jLabel11.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Vehicle No :");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(420, 290, 110, 40);

        veNonew.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jPanel4.add(veNonew);
        veNonew.setBounds(540, 290, 230, 40);

        jLabel12.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Telephone No  :");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(390, 220, 160, 40);

        cusnm.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jPanel4.add(cusnm);
        cusnm.setBounds(540, 150, 230, 40);

        bnew.setEditable(true);
        bnew.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        bnew.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "honda", "toyota", "suzuki", "nissan" }));
        bnew.setSelectedIndex(-1);
        jPanel4.add(bnew);
        bnew.setBounds(540, 360, 230, 40);

        jLabel6.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Vehicle Brand :");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(400, 360, 150, 40);

        jLabel7.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Vehicle name :");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(400, 440, 130, 40);

        vnmnew.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jPanel4.add(vnmnew);
        vnmnew.setBounds(540, 440, 230, 40);

        jButton4.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jButton4.setText("Save & Next");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4);
        jButton4.setBounds(630, 630, 171, 50);

        jButton5.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jButton5.setText("Home");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5);
        jButton5.setBounds(390, 630, 100, 50);

        jLabel14.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Vehicle Type :");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(400, 510, 130, 40);

        typenew.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "car", "van" }));
        jPanel4.add(typenew);
        typenew.setBounds(540, 510, 230, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sariya1200.jpg"))); // NOI18N
        jPanel4.add(jLabel10);
        jLabel10.setBounds(0, 0, 1200, 800);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(0, 0, 1210, 810);

        jTabbedPane1.addTab("New Customer", jPanel3);

        jPanel5.setLayout(null);

        jLabel48.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(240, 240, 240));
        jLabel48.setText("Insert Service");
        jPanel5.add(jLabel48);
        jLabel48.setBounds(270, 220, 290, 30);

        jLabel33.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(240, 240, 240));
        jLabel33.setText("Service ID:");
        jPanel5.add(jLabel33);
        jLabel33.setBounds(140, 300, 220, 24);

        sid.setEditable(false);
        sid.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel5.add(sid);
        sid.setBounds(240, 300, 250, 30);

        ser.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel5.add(ser);
        ser.setBounds(240, 340, 250, 30);

        jLabel15.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(240, 240, 240));
        jLabel15.setText("Service:");
        jPanel5.add(jLabel15);
        jLabel15.setBounds(160, 340, 200, 24);

        jLabel16.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(240, 240, 240));
        jLabel16.setText("Vehicle:");
        jPanel5.add(jLabel16);
        jLabel16.setBounds(160, 380, 200, 24);

        veh.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel5.add(veh);
        veh.setBounds(240, 380, 250, 30);

        jLabel17.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(240, 240, 240));
        jLabel17.setText("Full Service:");
        jPanel5.add(jLabel17);
        jLabel17.setBounds(120, 470, 240, 24);

        fs.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "YES", "NO" }));
        jPanel5.add(fs);
        fs.setBounds(240, 470, 250, 30);

        up.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel5.add(up);
        up.setBounds(240, 420, 250, 30);

        jLabel18.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(240, 240, 240));
        jLabel18.setText("Price:");
        jPanel5.add(jLabel18);
        jLabel18.setBounds(180, 420, 180, 24);

        jButton7.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jButton7.setText("ADD");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton7);
        jButton7.setBounds(260, 570, 230, 40);

        jLabel35.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(240, 240, 240));
        jLabel35.setText("Service:");
        jPanel5.add(jLabel35);
        jLabel35.setBounds(630, 290, 200, 30);

        uservice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userviceMousePressed(evt);
            }
        });
        uservice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userviceActionPerformed(evt);
            }
        });
        jPanel5.add(uservice);
        uservice.setBounds(710, 290, 250, 30);

        jLabel23.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(240, 240, 240));
        jLabel23.setText("Vehicle:");
        jPanel5.add(jLabel23);
        jLabel23.setBounds(630, 330, 200, 30);

        ufs.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "YES", "NO" }));
        ufs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ufsActionPerformed(evt);
            }
        });
        jPanel5.add(ufs);
        ufs.setBounds(710, 370, 250, 30);

        jLabel24.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(240, 240, 240));
        jLabel24.setText("Price:");
        jPanel5.add(jLabel24);
        jLabel24.setBounds(650, 420, 180, 30);

        uup.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel5.add(uup);
        uup.setBounds(710, 420, 250, 30);

        jButton9.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jButton9.setText("Update");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton9);
        jButton9.setBounds(720, 570, 230, 40);

        jLabel47.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(240, 240, 240));
        jLabel47.setText("Update Service");
        jPanel5.add(jLabel47);
        jLabel47.setBounds(730, 220, 310, 30);

        jLabel21.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(240, 240, 240));
        jLabel21.setText("Full Service:");
        jPanel5.add(jLabel21);
        jLabel21.setBounds(590, 370, 240, 30);

        jLabel36.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(240, 240, 240));
        jLabel36.setText("Service ID:");
        jPanel5.add(jLabel36);
        jLabel36.setBounds(610, 470, 220, 30);

        uveh.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                uvehItemStateChanged(evt);
            }
        });
        uveh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                uvehMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                uvehMousePressed(evt);
            }
        });
        uveh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uvehActionPerformed(evt);
            }
        });
        jPanel5.add(uveh);
        uveh.setBounds(710, 330, 250, 30);

        usid.setEditable(false);
        usid.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel5.add(usid);
        usid.setBounds(710, 470, 250, 30);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sariya1200.jpg"))); // NOI18N
        jPanel5.add(jLabel27);
        jLabel27.setBounds(0, 0, 1200, 800);

        jTabbedPane1.addTab("Manage Service", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1206, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noActionPerformed
    view v = new view();
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        DashBoard d = new DashBoard();
        d.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        DashBoard d = new DashBoard();
        d.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed
    int count = 0;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        no.setEditable(true);
        tel.setEditable(true);
        brand.setEditable(true);
        name.setEditable(true);
        cus.setEditable(false);
        vtype.setEditable(true);
        count++;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String today = new SimpleDateFormat("yyyy-MM-dd").format(Calendar.getInstance().getTime());
        Values.customer = cus.getText();
        if (no.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Pls fill the Vehicle No.");

        } else if (tel.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Pls fill the telephone No.");

        } else if (brand.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Pls fill the Vehicle Brand");

        } else if (name.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Pls fill the Vehicle name");

        } else if (count != 0) {
            v.update("UPDATE `customer` SET type='" + vtype.getText() + "',`telephone`='" + tel.getText() + "',`vehicleNo`='" + no.getText() + "',`vehicleBrand`='" + brand.getText() + "',`Model`='" + name.getText() + "',`date`='" + today + "', `Frequency`=Frequency+1 WHERE name='" + cus.getText() + "'");

            Service sv = new Service();
            sv.setVisible(true);

            this.dispose();
        } else {
            v.update("UPDATE `customer` SET `Frequency`=Frequency+1 WHERE name='" + cus.getText() + "'");

            Service sv = new Service();
            sv.setVisible(true);

            this.dispose();
        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ResultSet rs = v.getTable("SELECT `name`, `telephone`, `vehicleNo`, `vehicleBrand`, `Model`, `Frequency` FROM `customer` WHERE telephone='" + tel.getText() + "'");
        try {
            if (!rs.next()) {
                JOptionPane.showMessageDialog(null, "Customer not found");
                cus.setText("");
            } else {
                rs.beforeFirst();
                while (rs.next()) {
                    no.setText(rs.getString("vehicleNo"));
                    cus.setText(rs.getString("name"));
                    brand.setText(rs.getString("vehicleBrand"));
                    name.setText(rs.getString("Model"));
                    vtype.setText(rs.getString("Frequency"));
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(customerReg.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void cusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cusActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        String today = new SimpleDateFormat("yyyy-MM-dd").format(Calendar.getInstance().getTime());
        Values.customer = cusnm.getText();
        Values.vehicletype = typenew.getSelectedItem().toString();
        if (cusnm.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Customer Name is compulsory");
        } else if (telnew.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Telephone no is incorrrect!");
        } else if (veNonew.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Vehicle No is compulsory");
        } else if (bnew.getSelectedItem().equals("")) {
            JOptionPane.showMessageDialog(null, "Vehicle Brand is incorrect");
        } else if (vnmnew.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Vehicle name is incorrect");
        } else {
            v.insert("INSERT INTO `customer` VALUES('0','" + cusnm.getText() + "','" + telnew.getText() + "','" + veNonew.getText() + "','" + bnew.getSelectedItem() + "','" + vnmnew.getText() + "','" + typenew.getSelectedItem().toString() + "','" + today + "','1')");

            Service sv = new Service();
            sv.setVisible(true);

            this.dispose();
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void telnewKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telnewKeyPressed
  String ph=telnew.getText();
      
      int len=ph.length();
      char c= evt.getKeyChar();
      // check the character
      if(evt.getKeyChar()>='0'&& evt.getKeyChar()<='9'){
          
      if(len<10){
      telnew.setEditable(true);
      }else{
      telnew.setEditable(false);
      
      }
      }
      else{
      //erase number 'backspace work'
      if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
          // allo edit
          telnew.setEditable(true);
      }else{
           telnew.setEditable(false);
      }
      }        // TODO add your handling code here:
    }//GEN-LAST:event_telnewKeyPressed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (sid.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Service Id can not be empty");
        } else if (ser.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Service name can not be empty");
        } else if (veh.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Vehicle name can not be empty");
        } else if (fs.getSelectedItem().toString().equals("")) {
            JOptionPane.showMessageDialog(null, "Select whether full service or not!");
        } else if (up.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Price can not be empty");
        } else {
            String fullser = fs.getSelectedItem().toString();
            if (fullser.equals("NO")) {
                v.insert("INSERT INTO service values('" + sid.getText() + "','" + ser.getText() + "','" + veh.getText() + "','" + up.getText() + "')");
                JOptionPane.showMessageDialog(null, "New Service successfully added!");

                sid.setText("");
                ser.setText("");

                veh.setText("");
                fs.setSelectedItem("");
                up.setText("");
                loadCombo();

            } else {
                v.insert("INSERT INTO service values('" + sid.getText() + "','" + ser.getText() + "','" + veh.getText() + "','" + up.getText() + "')");
                v.insert("insert into fullservice values('" + sid.getText() + "')");
                JOptionPane.showMessageDialog(null, "New Service successfully added for fullservice!");

                sid.setText("");
                ser.setText("");

                veh.setText("");
                fs.setSelectedItem("");
                up.setText("");
                loadCombo();
            }

        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void userviceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userviceMousePressed

    }//GEN-LAST:event_userviceMousePressed

    private void userviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userviceActionPerformed

    }//GEN-LAST:event_userviceActionPerformed

    private void ufsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ufsActionPerformed
        if (ufs.getSelectedItem().toString().equals("NO")) {
            v.delete("delete from fullservice where id='" + ufs.getSelectedItem().toString() + "'");
        }
    }//GEN-LAST:event_ufsActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if (uup.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Pls enter the Unit price");
        } else {

            v.update("update service set Cost='" + uup.getText() + "' where Servicetype='" + uservice.getSelectedItem().toString() + "' && VehicleType='" + uveh.getSelectedItem().toString() + "'");
            JOptionPane.showMessageDialog(null, "Update successful");

        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void uvehItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_uvehItemStateChanged

    }//GEN-LAST:event_uvehItemStateChanged

    private void uvehMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uvehMouseClicked

    }//GEN-LAST:event_uvehMouseClicked

    private void uvehMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uvehMousePressed

    }//GEN-LAST:event_uvehMousePressed

    private void uvehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uvehActionPerformed
        if (uservice.getSelectedItem().toString().equals("")) {
            JOptionPane.showMessageDialog(null, "Please Select a service!");
        } else {
            try {
                if (!uveh.getSelectedItem().toString().equals("") && !uservice.getSelectedItem().toString().equals("")) {
                    ResultSet rs = v.getTable("select service.cost,service.ServiceID from service where VehicleType='" + uveh.getSelectedItem().toString() + "' AND ServiceType='" + uservice.getSelectedItem().toString() + "'");

                    while (rs.next()) {
                        if (rs.getString(1).equals("")) {
                            uup.setText("");
                            usid.setText("");
                        } else {
                            uup.setText(rs.getString(1));
                            usid.setText(rs.getString(2));
                        }
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(customerReg.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_uvehActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customerReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customerReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customerReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customerReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customerReg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox bnew;
    private javax.swing.JTextField brand;
    private javax.swing.JTextField cus;
    private javax.swing.JTextField cusnm;
    private javax.swing.JComboBox<String> fs;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField no;
    private javax.swing.JTextField ser;
    private javax.swing.JTextField sid;
    private javax.swing.JTextField tel;
    private javax.swing.JTextField telnew;
    private javax.swing.JComboBox typenew;
    private javax.swing.JComboBox ufs;
    private javax.swing.JTextField up;
    private javax.swing.JComboBox uservice;
    private javax.swing.JTextField usid;
    private javax.swing.JTextField uup;
    private javax.swing.JComboBox<String> uveh;
    private javax.swing.JTextField veNonew;
    private javax.swing.JTextField veh;
    private javax.swing.JTextField vnmnew;
    private javax.swing.JTextField vtype;
    // End of variables declaration//GEN-END:variables
}
