/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ServiceCenter;

/**
 *
 * @author Shehan Atapattu
 */
public class DashBoard extends javax.swing.JFrame {

    String user = Values.usernm;

    /**
     * Creates new form cashierHome
     */
    public DashBoard() {
        initComponents();
        userlbl.setText(user);
        arrangeHome();
    }

    public void arrangeHome() {
        if (user.equals("Cashier")) {

            stock.setEnabled(false);
            supplier.setEnabled(false);
            supplier.setToolTipText("Administrator access only");
        } else if (user.equals("Stock Handler")) {
            sales.setEnabled(false);
            service.setEnabled(false);
            supplier.setEnabled(false);
            supplier.setToolTipText("Administrator access only");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sales = new javax.swing.JButton();
        service = new javax.swing.JButton();
        userlbl = new javax.swing.JLabel();
        reports = new javax.swing.JButton();
        supplier = new javax.swing.JButton();
        stock = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 710));

        jPanel1.setMinimumSize(new java.awt.Dimension(800, 800));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 800));
        jPanel1.setLayout(null);

        sales.setBackground(new java.awt.Color(255, 255, 255));
        sales.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        sales.setText("Sales");
        sales.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        sales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesActionPerformed(evt);
            }
        });
        jPanel1.add(sales);
        sales.setBounds(220, 220, 310, 40);

        service.setBackground(new java.awt.Color(255, 255, 255));
        service.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        service.setText("Service");
        service.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        service.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceActionPerformed(evt);
            }
        });
        jPanel1.add(service);
        service.setBounds(220, 280, 310, 40);

        userlbl.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        userlbl.setForeground(new java.awt.Color(153, 153, 255));
        jPanel1.add(userlbl);
        userlbl.setBounds(440, 160, 240, 30);

        reports.setBackground(new java.awt.Color(255, 255, 255));
        reports.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        reports.setText("Reports");
        reports.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        reports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportsActionPerformed(evt);
            }
        });
        jPanel1.add(reports);
        reports.setBounds(220, 460, 310, 40);

        supplier.setBackground(new java.awt.Color(255, 255, 255));
        supplier.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        supplier.setText("Supplier");
        supplier.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierActionPerformed(evt);
            }
        });
        jPanel1.add(supplier);
        supplier.setBounds(220, 340, 310, 40);

        stock.setBackground(new java.awt.Color(255, 255, 255));
        stock.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        stock.setText("Stock");
        stock.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockActionPerformed(evt);
            }
        });
        jPanel1.add(stock);
        stock.setBounds(220, 400, 310, 40);

        jButton1.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        jButton1.setText("Log Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(310, 600, 130, 33);

        jLabel1.setFont(new java.awt.Font("Ebrima", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("WELCOME");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(320, 150, 120, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sariya1200.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(-220, 0, 1090, 790);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void salesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesActionPerformed
        // TODO add your handling code here:
        sales sl = new sales();
        sl.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_salesActionPerformed

    private void serviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceActionPerformed
        // TODO add your handling code here:
        customerReg sv = new customerReg();
        sv.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_serviceActionPerformed

    private void reportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportsActionPerformed
        // TODO add your handling code here:
        if (user.equals("Cashier")) {
            CshrReport cr = new CshrReport();
            cr.setVisible(true);
            setVisible(false);
        } else if (user.equals("Stock Handler")) {
            StkReport sr = new StkReport();
            sr.setVisible(true);
            setVisible(false);
        } else {
            Allreports ar = new Allreports();
            ar.setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_reportsActionPerformed

    private void supplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierActionPerformed
        sup sp = new sup();
        sp.setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_supplierActionPerformed

    private void stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockActionPerformed
        StockUpdate st = new StockUpdate();
        st.setVisible(true);
        setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_stockActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Login ll = new Login();
        ll.setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton reports;
    private javax.swing.JButton sales;
    private javax.swing.JButton service;
    private javax.swing.JButton stock;
    private javax.swing.JButton supplier;
    private javax.swing.JLabel userlbl;
    // End of variables declaration//GEN-END:variables
}
