/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ServiceCenter;

/**
 *
 * @author Shehan Atapattu
 */
public class Reorder extends javax.swing.JFrame {

    /**
     * Creates new form Reorder
     */
    public Reorder() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel13 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton11 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1205, 843));
        setPreferredSize(new java.awt.Dimension(1205, 843));

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3), "Re-Order Level Reached Items", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel13.setMinimumSize(new java.awt.Dimension(1205, 843));
        jPanel13.setPreferredSize(new java.awt.Dimension(1205, 843));
        jPanel13.setLayout(null);

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Items", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel15.setForeground(new java.awt.Color(204, 204, 204));
        jPanel15.setLayout(null);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Name", "Quantity"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jPanel15.add(jScrollPane3);
        jScrollPane3.setBounds(18, 30, 1050, 300);

        jPanel13.add(jPanel15);
        jPanel15.setBounds(70, 150, 1080, 360);

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton11.setText("Send Mail");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton11);
        jButton11.setBounds(890, 640, 119, 46);

        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Item Name:");
        jPanel13.add(jLabel7);
        jLabel7.setBounds(440, 540, 70, 14);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton4.setText("Home");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton4);
        jButton4.setBounds(120, 650, 92, 46);
        jPanel13.add(jTextField4);
        jTextField4.setBounds(520, 540, 200, 20);
        jPanel13.add(jTextField5);
        jTextField5.setBounds(810, 540, 100, 20);

        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Qty:");
        jPanel13.add(jLabel8);
        jLabel8.setBounds(770, 540, 40, 20);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton5.setText("Exit");
        jPanel13.add(jButton5);
        jButton5.setBounds(240, 650, 92, 46);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sariya1200.jpg"))); // NOI18N
        jPanel13.add(jLabel5);
        jLabel5.setBounds(0, 0, 1210, 810);

        jTabbedPane1.addTab("Reorder Items", jPanel13);

        jPanel1.setMinimumSize(new java.awt.Dimension(1205, 843));
        jPanel1.setPreferredSize(new java.awt.Dimension(1205, 843));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Item:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(190, 120, 37, 19);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Qty:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(200, 180, 40, 19);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(250, 170, 199, 38);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(250, 110, 199, 38);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(310, 270, 92, 46);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton2.setText("Home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(70, 670, 92, 46);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton3.setText("Exit");
        jPanel1.add(jButton3);
        jButton3.setBounds(170, 670, 92, 46);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Invoice No:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(160, 70, 55, 14);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(250, 60, 199, 32);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Item", "Qty", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(694, 65, 452, 144);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton6.setText("Return");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(910, 670, 92, 46);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Grand Total:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(889, 238, 60, 14);

        jTextField3.setEditable(false);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(995, 227, 151, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sariya1200.jpg"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 0, 1200, 800);

        jTabbedPane1.addTab("Return Items", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 852, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // Re-Order level Report

//        JFileChooser dialog = new JFileChooser();
//        dialog.setSelectedFile(new File("ReOrder Report "+dateChooserCombo7.getText()+".pdf"));
//        int dialogResult = dialog.showSaveDialog(null);
//        if (dialogResult==JFileChooser.APPROVE_OPTION){
//            String filePath = dialog.getSelectedFile().getPath();
//            Document document = new Document(PageSize.A4, 50, 50, 140, 140);
//
//            //Creation of PdfWriter object
//            try {
//
//                PdfWriter writer = PdfWriter.getInstance(document,
//                    new FileOutputStream(filePath));
//                document.open();
//                writer.setPageEvent(new MyPdfPageEventHelper("Service.png"));
//            } catch (Exception e) {
//                System.out.println(e);
//            }
//
//            Paragraph title2 = new Paragraph("Re-Order Report",
//                FontFactory.getFont(FontFactory.HELVETICA,
//                    18, Font.ITALIC, new CMYKColor(75, 68, 67,90)));
//            Chapter chapter2 = new Chapter(title2, 1);
//            Paragraph title = new Paragraph("Date : "+dateChooserCombo7.getText(),
//                FontFactory.getFont(FontFactory.TIMES_ROMAN,
//                    14, Font.NORMAL, new CMYKColor(75, 68, 67,90)));
//
//            try {
//                title2.setAlignment(Element.ALIGN_CENTER);
//                document.add(title2);
//
//                PdfPTable t = new PdfPTable(2);
//                t.setSpacingBefore(5);
//                t.setSpacingAfter(5);
//
//                PdfPTable t1 = new PdfPTable(2);
//                t1.setSpacingBefore(5);
//                t1.setSpacingAfter(5);
//
//                Paragraph title3 = new Paragraph("Item Type : Spare Parts",
//                    FontFactory.getFont(FontFactory.HELVETICA,
//                        14, Font.NORMAL, new CMYKColor(75, 68, 67,90)));
//                Paragraph title4 = new Paragraph("Item Type : Lubricants",
//                    FontFactory.getFont(FontFactory.HELVETICA,
//                        14, Font.NORMAL, new CMYKColor(75, 68, 67,90)));
//                Chapter chapter3 = new Chapter(title3, 1);
//                //chapter1.setNumberDepth(0);
//                document.add(title);
//
//                //t1.addCell("ItemNo");
//                t.addCell("Item Name");
//                t.addCell("Amount");
//
//                t1.addCell("Item Name");
//                t1.addCell("Amount");
//
//                for(int i = 0; i < jTable3.getRowCount(); i++ ){
//                    String ItemName = jTable3.getValueAt(i, 0).toString();
//                    String amnt = jTable3.getValueAt(i, 1).toString();
//
//                    //t1.addCell(orderID);
//                    t.addCell(ItemName);
//                    t.addCell(amnt);
//
//                }
//                document.add(title3);
//                document.add(Chunk.NEWLINE);
//
//                document.add(t);
//                for(int i = 0; i < jTable4.getRowCount(); i++ ){
//                    String ItemName = jTable4.getValueAt(i, 0).toString();
//                    String amnt = jTable4.getValueAt(i, 1).toString();
//
//                    t1.addCell(ItemName);
//                    t1.addCell(amnt);
//
//                }
//
//                document.add(Chunk.NEWLINE);
//                document.add(title4);
//                document.add(Chunk.NEWLINE);
//                document.add(t1);
//                document.close();
//            }
//            catch(Exception e){
//                e.printStackTrace();
//            }
//        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        DashBoard dbd=new DashBoard();
        dbd.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        DashBoard dbd=new DashBoard();
        dbd.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reorder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
