/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ServiceCenter;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Font;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Shehan Atapattu
 */
public class StkReport extends javax.swing.JFrame {

    /**
     * Creates new form StkReport
     */
    public StkReport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        pdatefrom = new datechooser.beans.DateChooserCombo();
        pdateto = new datechooser.beans.DateChooserCombo();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel29 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        ptotal = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        dateChooserCombo9 = new datechooser.beans.DateChooserCombo();
        jLabel31 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        dateChooserCombo7 = new datechooser.beans.DateChooserCombo();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        dateChooserCombo8 = new datechooser.beans.DateChooserCombo();
        jLabel26 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jButton19 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1205, 843));

        jPanel1.setMinimumSize(new java.awt.Dimension(1205, 843));
        jPanel1.setPreferredSize(new java.awt.Dimension(1205, 843));
        jPanel1.setLayout(null);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jPanel2.setLayout(null);

        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        jPanel7.setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Get Details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton1);
        jButton1.setBounds(690, 100, 131, 45);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Select Time Period");
        jPanel7.add(jLabel15);
        jLabel15.setBounds(60, 10, 140, 24);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("To");
        jPanel7.add(jLabel16);
        jLabel16.setBounds(200, 50, 21, 23);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("From");
        jPanel7.add(jLabel17);
        jLabel17.setBounds(10, 50, 44, 30);
        jPanel7.add(pdatefrom);
        pdatefrom.setBounds(58, 53, 102, 20);
        jPanel7.add(pdateto);
        pdateto.setBounds(227, 54, 85, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Stock Items", "Date" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel7.add(jComboBox1);
        jComboBox1.setBounds(450, 40, 110, 30);

        jLabel29.setForeground(new java.awt.Color(240, 240, 240));
        jLabel29.setText("Report By:");
        jPanel7.add(jLabel29);
        jLabel29.setBounds(370, 50, 60, 20);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sariya1200.jpg"))); // NOI18N
        jPanel7.add(jLabel2);
        jLabel2.setBounds(-120, -10, 1000, 180);

        jPanel2.add(jPanel7);
        jPanel7.setBounds(160, 90, 840, 160);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ItemId", "ItemName", "StockPurchases", "Cost"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(90, 280, 1040, 260);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("Report");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(890, 640, 93, 57);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("Home");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(90, 660, 85, 31);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setText("Exit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(200, 660, 67, 31);

        ptotal.setEditable(false);
        jPanel2.add(ptotal);
        ptotal.setBounds(820, 570, 170, 30);

        jLabel28.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(240, 240, 240));
        jLabel28.setText("Total: Rs");
        jPanel2.add(jLabel28);
        jLabel28.setBounds(740, 570, 90, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sariya1200.jpg"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 1210, 800);

        jTabbedPane1.addTab("Purchases", jPanel2);

        jPanel3.setLayout(null);

        jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        jPanel17.setLayout(null);

        jButton9.setBackground(new java.awt.Color(204, 204, 204));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton9.setText("Get Details");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel17.add(jButton9);
        jButton9.setBounds(600, 90, 131, 53);

        dateChooserCombo9.setEnabled(false);
        jPanel17.add(dateChooserCombo9);
        dateChooserCombo9.setBounds(110, 90, 140, 30);

        jLabel31.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Date:");
        jPanel17.add(jLabel31);
        jLabel31.setBounds(50, 90, 50, 24);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sariya1200.jpg"))); // NOI18N
        jPanel17.add(jLabel3);
        jLabel3.setBounds(-50, 0, 1230, 190);

        jPanel3.add(jPanel17);
        jPanel17.setBounds(150, 130, 970, 190);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ItemNo", "Item Name", "Available Quantity"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        jPanel3.add(jScrollPane5);
        jScrollPane5.setBounds(80, 330, 1040, 300);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton7.setText("Home");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7);
        jButton7.setBounds(32, 714, 85, 31);

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton8.setText("Exit");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8);
        jButton8.setBounds(135, 714, 67, 31);

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton10.setText("Report");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton10);
        jButton10.setBounds(930, 680, 93, 57);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sariya1200.jpg"))); // NOI18N
        jPanel3.add(jLabel4);
        jLabel4.setBounds(0, 0, 1200, 810);

        jTabbedPane1.addTab("Stock Report", jPanel3);

        jPanel4.setLayout(null);
        jPanel4.add(dateChooserCombo7);
        dateChooserCombo7.setBounds(335, 172, 155, 20);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("From");
        jPanel4.add(jLabel24);
        jLabel24.setBounds(275, 172, 36, 20);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Select Time Period");
        jPanel4.add(jLabel27);
        jLabel27.setBounds(245, 122, 135, 24);
        jPanel4.add(dateChooserCombo8);
        dateChooserCombo8.setBounds(575, 172, 155, 20);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("To");
        jPanel4.add(jLabel26);
        jLabel26.setBounds(535, 172, 18, 26);

        jButton17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton17.setText("View Report");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton17);
        jButton17.setBounds(805, 162, 143, 42);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Item", "Qty", "Total"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jPanel4.add(jScrollPane4);
        jScrollPane4.setBounds(227, 293, 818, 172);

        jButton19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton19.setText("Exit");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton19);
        jButton19.setBounds(329, 634, 130, 60);

        jButton18.setBackground(new java.awt.Color(0, 51, 51));
        jButton18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton18.setText("Home");
        jButton18.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton18);
        jButton18.setBounds(169, 634, 120, 60);

        jButton20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton20.setText("Report Generate");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton20);
        jButton20.setBounds(849, 631, 183, 60);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sariya1200.jpg"))); // NOI18N
        jPanel4.add(jLabel13);
        jLabel13.setBounds(2, 3, 1200, 800);

        jTabbedPane1.addTab("Removed Items", jPanel4);

        jPanel1.add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 1210, 850);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        view v = new view();
        String dt1 = new SimpleDateFormat("yyyy-MM-dd").format(pdatefrom.getSelectedDate().getTime());
        String dt2 = new SimpleDateFormat("yyyy-MM-dd").format(pdateto.getSelectedDate().getTime());
        if (jComboBox1.getSelectedItem().toString().equals("Stock Items")) {
            ResultSet rs1 = v.getTable("SELECT item.ItemName,item.Brand,item.Model, SUM(contain.Qty) as Qty, contain.price,SUM(contain.Qty*contain.price) as total FROM `contain` INNER JOIN iteminvoice ON contain.InvoiceNo=iteminvoice.InvoiceNo INNER JOIN item ON item.ItemID=contain.ItemID WHERE iteminvoice.date BETWEEN '" + dt1 + "' AND '" + dt2 + "' GROUP BY contain.ItemID");
            jTable1.setModel(DbUtils.resultSetToTableModel(rs1));
            jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
            double total = 0.0;
            for (int i = 0; i < jTable1.getRowCount(); i++) {
                total = total + Double.valueOf(jTable1.getModel().getValueAt(i, 5).toString());
            }
            ptotal.setText(String.valueOf(total));
        } else {

            ResultSet rs2 = v.getTable("SELECT iteminvoice.date,item.ItemName,item.Brand,item.Model, SUM(contain.Qty) as Qty, contain.price,SUM(contain.Qty*contain.price) AS total FROM `contain` INNER JOIN iteminvoice ON contain.InvoiceNo=iteminvoice.InvoiceNo INNER JOIN item ON item.ItemID=contain.ItemID WHERE iteminvoice.date BETWEEN '" + dt1 + "' AND '" + dt2 + "' GROUP BY iteminvoice.date");
            jTable1.setModel(DbUtils.resultSetToTableModel(rs2));
            jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
            double total = 0.0;
            for (int i = 0; i < jTable1.getRowCount(); i++) {
                total = total + Double.valueOf(jTable1.getModel().getValueAt(i, 6).toString());
            }
            ptotal.setText(String.valueOf(total));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String today = new SimpleDateFormat("yyyy-MM-dd").format(Calendar.getInstance().getTime());
        JFileChooser dialog = new JFileChooser();
        dialog.setSelectedFile(new File("purchase report by " + jComboBox1.getSelectedItem().toString() + " - " + today + ".pdf"));
        int dialogResult = dialog.showSaveDialog(null);
        if (dialogResult == JFileChooser.APPROVE_OPTION) {
            String filePath = dialog.getSelectedFile().getPath();

            try {

                Document myDocument = new Document();

                PdfWriter myWriter = PdfWriter.getInstance(myDocument, new FileOutputStream(filePath));
                myDocument.open();

                myWriter.setPageEvent(new MyPdfPageEventHelper("saman.png"));
                myDocument.add(new Paragraph("\n\n\n\n\n\n\n\n\n"));

                myDocument.add(new Paragraph("", FontFactory.getFont(FontFactory.TIMES_BOLD, 20, Font.BOLD)));
                myDocument.add(new Paragraph("", FontFactory.getFont(FontFactory.TIMES_BOLD, 15, Font.PLAIN)));
                myDocument.add(new Paragraph("", FontFactory.getFont(FontFactory.TIMES_BOLD, 15, Font.PLAIN)));
                Paragraph ph = new Paragraph("PURCHASES\n", FontFactory.getFont(FontFactory.TIMES_BOLD, 20, Font.BOLD));
                ph.setAlignment(Paragraph.ALIGN_CENTER);
                myDocument.add(ph);

                myDocument.add(new Paragraph("\n\n"));
                if (jComboBox1.getSelectedItem().toString().equals("Stock Items")) {
                    PdfPTable table = new PdfPTable(6);

                    table.setWidthPercentage(100);
                    float[] columnWidths = new float[]{5, 5, 5, 5, 5, 5};
                    table.setWidths(columnWidths);
                    String from = new SimpleDateFormat("dd-MM-yyyy").format(pdatefrom.getSelectedDate().getTime());
                    String to = new SimpleDateFormat("dd-MM-yyyy").format(pdateto.getSelectedDate().getTime());

                    PdfPTable table3 = new PdfPTable(2);
                    table3.setWidthPercentage(100);
                    float[] columnWidths3 = new float[]{12, 4};
                    table3.setWidths(columnWidths3);

                    PdfPCell cell1 = new PdfPCell(new Paragraph("from: " + from, FontFactory.getFont(FontFactory.TIMES, 12)));

                    PdfPCell cell2 = new PdfPCell(new Paragraph("To: " + to, FontFactory.getFont(FontFactory.TIMES, 12)));
                    cell2.setHorizontalAlignment(Element.ALIGN_LEFT);
                    cell1.setBorderColor(BaseColor.WHITE);
                    cell2.setBorderColor(BaseColor.WHITE);

                    table3.addCell(cell1);
                    table3.addCell(cell2);

                    myDocument.add(table3);
                    myDocument.add(new Paragraph("\n\n"));
                    // myDocument.add(new Paragraph(new Date().toString()));
                    // myDocument.add(new Paragraph("--------------------------------------------------------------------------------------------------------------------------------"));
                    table.addCell(new PdfPCell(new Paragraph("Item Name", FontFactory.getFont(FontFactory.TIMES_ROMAN, 9, Font.BOLD))));
                    table.addCell(new PdfPCell(new Paragraph("Brand", FontFactory.getFont(FontFactory.TIMES_ROMAN, 9, Font.BOLD))));
                    table.addCell(new PdfPCell(new Paragraph("Model", FontFactory.getFont(FontFactory.TIMES_ROMAN, 9, Font.BOLD))));
                    table.addCell(new PdfPCell(new Paragraph("Qty", FontFactory.getFont(FontFactory.TIMES_ROMAN, 9, Font.BOLD))));
                    table.addCell(new PdfPCell(new Paragraph("Unit Price", FontFactory.getFont(FontFactory.TIMES_ROMAN, 9, Font.BOLD))));
                    table.addCell(new PdfPCell(new Paragraph("Total(Rs)", FontFactory.getFont(FontFactory.TIMES_ROMAN, 9, Font.BOLD))));

                    for (int i = 0; i < jTable1.getRowCount(); i++) {

                        table.addCell(new PdfPCell(new Paragraph(jTable1.getValueAt(i, 0).toString(), FontFactory.getFont(FontFactory.TIMES_ROMAN, 8, Font.PLAIN))));
                        table.addCell(new PdfPCell(new Paragraph(jTable1.getValueAt(i, 1).toString(), FontFactory.getFont(FontFactory.TIMES_ROMAN, 8, Font.PLAIN))));
                        table.addCell(new PdfPCell(new Paragraph(jTable1.getValueAt(i, 2).toString(), FontFactory.getFont(FontFactory.TIMES_ROMAN, 8, Font.PLAIN))));
                        table.addCell(new PdfPCell(new Paragraph(jTable1.getValueAt(i, 3).toString(), FontFactory.getFont(FontFactory.TIMES_ROMAN, 8, Font.PLAIN))));
                        table.addCell(new PdfPCell(new Paragraph(jTable1.getValueAt(i, 4).toString(), FontFactory.getFont(FontFactory.TIMES_ROMAN, 8, Font.PLAIN))));
                        table.addCell(new PdfPCell(new Paragraph(jTable1.getValueAt(i, 5).toString(), FontFactory.getFont(FontFactory.TIMES_ROMAN, 8, Font.PLAIN))));

                    }

                    myDocument.add(table);
                    myDocument.add(new Paragraph("\n"));
                    Paragraph pp = new Paragraph("Total Purchases:Rs " + ptotal.getText() + "", FontFactory.getFont(FontFactory.TIMES, 12));
                    pp.setAlignment(Element.ALIGN_RIGHT);
                    myDocument.add(pp);
                    myDocument.add(new Paragraph("\n\n"));

                    Paragraph pt = new Paragraph("Thank You!\n", FontFactory.getFont(FontFactory.TIMES, 12));
                    pt.setAlignment(Paragraph.ALIGN_CENTER);
                    myDocument.add(pt);
                    myDocument.add(new Paragraph("\n"));

                    myDocument.add(new Paragraph("--------------------------------------------------------------------------------------------------------------------------------"));

                    myDocument.close();

                } else {
                    PdfPTable table5 = new PdfPTable(6);

                    String from = new SimpleDateFormat("dd-MM-yyyy").format(pdatefrom.getSelectedDate().getTime());
                    String to = new SimpleDateFormat("dd-MM-yyyy").format(pdateto.getSelectedDate().getTime());

                    PdfPTable table3 = new PdfPTable(2);
                    table3.setWidthPercentage(100);
                    float[] columnWidths3 = new float[]{12, 4};
                    table3.setWidths(columnWidths3);

                    PdfPCell cell1 = new PdfPCell(new Paragraph("from: " + from, FontFactory.getFont(FontFactory.TIMES, 12)));
                    //plo.setAlignment(Paragraph.ALIGN_RIGHT);
                    // myDocument.add(plo);

                    PdfPCell cell2 = new PdfPCell(new Paragraph("To: " + to, FontFactory.getFont(FontFactory.TIMES, 12)));
                    cell2.setHorizontalAlignment(Element.ALIGN_LEFT);
                    cell1.setBorderColor(BaseColor.WHITE);
                    cell2.setBorderColor(BaseColor.WHITE);

                    table3.addCell(cell1);
                    table3.addCell(cell2);

                    myDocument.add(table3);

                    myDocument.add(new Paragraph("\n\n"));
                    PdfPTable table = new PdfPTable(7);

                    table.setWidthPercentage(100);
                    float[] columnWidths = new float[]{5, 5, 5, 5, 5, 5, 5};
                    table.setWidths(columnWidths);

                    // myDocument.add(new Paragraph(new Date().toString()));
                    //   myDocument.add(new Paragraph("--------------------------------------------------------------------------------------------------------------------------------"));
                    table.addCell(new PdfPCell(new Paragraph("Date", FontFactory.getFont(FontFactory.TIMES_ROMAN, 9, Font.BOLD))));
                    table.addCell(new PdfPCell(new Paragraph("Item Name", FontFactory.getFont(FontFactory.TIMES_ROMAN, 9, Font.BOLD))));
                    table.addCell(new PdfPCell(new Paragraph("Brand", FontFactory.getFont(FontFactory.TIMES_ROMAN, 9, Font.BOLD))));
                    table.addCell(new PdfPCell(new Paragraph("Model", FontFactory.getFont(FontFactory.TIMES_ROMAN, 9, Font.BOLD))));
                    table.addCell(new PdfPCell(new Paragraph("Qty", FontFactory.getFont(FontFactory.TIMES_ROMAN, 9, Font.BOLD))));
                    table.addCell(new PdfPCell(new Paragraph("Unit Price", FontFactory.getFont(FontFactory.TIMES_ROMAN, 9, Font.BOLD))));
                    table.addCell(new PdfPCell(new Paragraph("Total", FontFactory.getFont(FontFactory.TIMES_ROMAN, 9, Font.BOLD))));

                    for (int i = 0; i < jTable1.getRowCount(); i++) {

                        table.addCell(new PdfPCell(new Paragraph(jTable1.getValueAt(i, 0).toString(), FontFactory.getFont(FontFactory.TIMES_ROMAN, 8, Font.PLAIN))));
                        table.addCell(new PdfPCell(new Paragraph(jTable1.getValueAt(i, 1).toString(), FontFactory.getFont(FontFactory.TIMES_ROMAN, 8, Font.PLAIN))));
                        table.addCell(new PdfPCell(new Paragraph(jTable1.getValueAt(i, 2).toString(), FontFactory.getFont(FontFactory.TIMES_ROMAN, 8, Font.PLAIN))));
                        table.addCell(new PdfPCell(new Paragraph(jTable1.getValueAt(i, 3).toString(), FontFactory.getFont(FontFactory.TIMES_ROMAN, 8, Font.PLAIN))));
                        table.addCell(new PdfPCell(new Paragraph(jTable1.getValueAt(i, 4).toString(), FontFactory.getFont(FontFactory.TIMES_ROMAN, 8, Font.PLAIN))));
                        table.addCell(new PdfPCell(new Paragraph(jTable1.getValueAt(i, 5).toString(), FontFactory.getFont(FontFactory.TIMES_ROMAN, 8, Font.PLAIN))));
                        table.addCell(new PdfPCell(new Paragraph(jTable1.getValueAt(i, 6).toString(), FontFactory.getFont(FontFactory.TIMES_ROMAN, 8, Font.PLAIN))));

                    }

                    myDocument.add(table);
                    myDocument.add(new Paragraph("\n"));
                    Paragraph pp = new Paragraph("Total Purchases: " + ptotal.getText() + "", FontFactory.getFont(FontFactory.TIMES, 12));
                    pp.setAlignment(Element.ALIGN_RIGHT);
                    myDocument.add(pp);
                    myDocument.add(new Paragraph("\n\n"));

                    Paragraph pt = new Paragraph("Thank You!\n", FontFactory.getFont(FontFactory.TIMES, 12));
                    pt.setAlignment(Paragraph.ALIGN_CENTER);
                    myDocument.add(pt);
                    myDocument.add(new Paragraph("\n"));

                    myDocument.add(new Paragraph("--------------------------------------------------------------------------------------------------------------------------------"));

                    myDocument.close();

                }

                JOptionPane.showMessageDialog(null, "Report was successfully generated");

            } catch (DocumentException ex) {
                Logger.getLogger(Allreports.class.getName()).log(Level.SEVERE, null, ex);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Allreports.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        DashBoard dbd=new DashBoard();
        dbd.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed
   int count = 0;
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
          view v = new view();
        try {
            ResultSet rs = v.getTable("SELECT `ItemID`, `ItemName`, `Brand`, `Model`, `TotalStock` as 'Available Qty' FROM `item`");
            jTable5.setModel(DbUtils.resultSetToTableModel(rs));
            count++;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error!! try again");
            count = 0;
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        
        String today = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(Calendar.getInstance().getTime());
        JFileChooser dialog = new JFileChooser();
        dialog.setSelectedFile(new File("stock report - " + today + ".pdf"));
        int dialogResult = dialog.showSaveDialog(null);
        if (dialogResult == JFileChooser.APPROVE_OPTION) {
            String filePath = dialog.getSelectedFile().getPath();

            try {

                Document myDocument = new Document();

                PdfWriter myWriter = PdfWriter.getInstance(myDocument, new FileOutputStream(filePath));
                myDocument.open();

                myWriter.setPageEvent(new MyPdfPageEventHelper("saman.png"));
                myDocument.add(new Paragraph("\n\n\n\n\n\n\n\n\n"));

                myDocument.add(new Paragraph("", FontFactory.getFont(FontFactory.TIMES_BOLD, 20, Font.BOLD)));
                myDocument.add(new Paragraph("", FontFactory.getFont(FontFactory.TIMES_BOLD, 15, Font.PLAIN)));
                myDocument.add(new Paragraph("", FontFactory.getFont(FontFactory.TIMES_BOLD, 15, Font.PLAIN)));

                Paragraph ph = new Paragraph("Stock Report\n", FontFactory.getFont(FontFactory.TIMES_BOLD, 20, Font.BOLD));
                ph.setAlignment(Paragraph.ALIGN_CENTER);
                myDocument.add(ph);
                myDocument.add(new Paragraph("\n\n"));
                PdfPTable table = new PdfPTable(5);

                table.setWidthPercentage(100);
                float[] columnWidths = new float[]{5, 5, 5, 5, 5};
                table.setWidths(columnWidths);

                String adf = new SimpleDateFormat("dd-MM-yyyy").format(new Date());

                myDocument.add(new Paragraph("Date :" + adf + "\n", FontFactory.getFont(FontFactory.TIMES, 12)));
                myDocument.add(new Paragraph("\n\n"));
                //  myDocument.add(new Paragraph(new Date().toString()));
                // myDocument.add(new Paragraph("--------------------------------------------------------------------------------------------------------------------------------"));
                table.addCell(new PdfPCell(new Paragraph("Item ID", FontFactory.getFont(FontFactory.TIMES_ROMAN, 9, Font.BOLD))));
                table.addCell(new PdfPCell(new Paragraph("Item Name", FontFactory.getFont(FontFactory.TIMES_ROMAN, 9, Font.BOLD))));
                table.addCell(new PdfPCell(new Paragraph("Brand", FontFactory.getFont(FontFactory.TIMES_ROMAN, 9, Font.BOLD))));
                table.addCell(new PdfPCell(new Paragraph("Model", FontFactory.getFont(FontFactory.TIMES_ROMAN, 9, Font.BOLD))));
                table.addCell(new PdfPCell(new Paragraph("Available Qty", FontFactory.getFont(FontFactory.TIMES_ROMAN, 9, Font.BOLD))));

                for (int i = 0; i < jTable5.getRowCount(); i++) {

                    table.addCell(new PdfPCell(new Paragraph(jTable5.getValueAt(i, 0).toString(), FontFactory.getFont(FontFactory.TIMES_ROMAN, 8, Font.PLAIN))));
                    table.addCell(new PdfPCell(new Paragraph(jTable5.getValueAt(i, 1).toString(), FontFactory.getFont(FontFactory.TIMES_ROMAN, 8, Font.PLAIN))));
                    table.addCell(new PdfPCell(new Paragraph(jTable5.getValueAt(i, 2).toString(), FontFactory.getFont(FontFactory.TIMES_ROMAN, 8, Font.PLAIN))));
                    table.addCell(new PdfPCell(new Paragraph(jTable5.getValueAt(i, 3).toString(), FontFactory.getFont(FontFactory.TIMES_ROMAN, 8, Font.PLAIN))));
                    table.addCell(new PdfPCell(new Paragraph(jTable5.getValueAt(i, 4).toString(), FontFactory.getFont(FontFactory.TIMES_ROMAN, 8, Font.PLAIN))));

                }

                myDocument.add(table);

                // myDocument.add(new Paragraph("--------------------------------------------------------------------------------------------------------------------------------"));
                myDocument.close();

                JOptionPane.showMessageDialog(null, "Report was successfully generated");

            } catch (DocumentException ex) {
                Logger.getLogger(Allreports.class.getName()).log(Level.SEVERE, null, ex);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Allreports.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton10ActionPerformed
int c=0;
    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
         view v = new view();
        String dt1 = new SimpleDateFormat("yyyy-MM-dd").format(dateChooserCombo7.getSelectedDate().getTime());
        String dt2 = new SimpleDateFormat("yyyy-MM-dd").format(dateChooserCombo8.getSelectedDate().getTime());
        try {
            ResultSet rs = v.getTable("SELECT removed.itemId,item.Brand,item.Model,removed.Qty,removed.date,removed.reason FROM item INNER JOIN removed on item.itemId=removed.itemId WHERE removed.date BETWEEN '" + dt1 + "' AND '" + dt2 + "'");
            jTable4.setModel(DbUtils.resultSetToTableModel(rs));
            c++;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error!! try again");
            c = 0;
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StkReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StkReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StkReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StkReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StkReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo dateChooserCombo7;
    private datechooser.beans.DateChooserCombo dateChooserCombo8;
    private datechooser.beans.DateChooserCombo dateChooserCombo9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private datechooser.beans.DateChooserCombo pdatefrom;
    private datechooser.beans.DateChooserCombo pdateto;
    private javax.swing.JTextField ptotal;
    // End of variables declaration//GEN-END:variables
}
