/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ServiceCenter;

import com.itextpdf.text.Chapter;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.CMYKColor;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Shehan Atapattu
 */
public class StockUpdate extends javax.swing.JFrame {

    /**
     * Creates new form StockUpdate
     */
    public StockUpdate() {

        initComponents();
        try {
            ResultSet rs = v.getTable("SELECT count(`ItemID`) FROM `item`");
            int id = 0;
            while(rs.next()){
            id = rs.getInt(1) + 1;
            }
            itid.setText(String.valueOf(id));
        } catch (SQLException ex) {
            Logger.getLogger(StockUpdate.class.getName()).log(Level.SEVERE, null, ex);
        }

        ResultSet rs1 = v.getTable("SELECT SupplierID,`Name` FROM `supplier` WHERE `isDeleted`='0'");

        try {
            su.removeAllItems();
            sup.removeAllItems();

            while (rs1.next()) {
                su.addItem(rs1.getString(1) + " " + rs1.getString(2));
                sup.addItem(rs1.getString(1) + " " + rs1.getString(2));

            }
        } catch (SQLException ex) {
            Logger.getLogger(StockUpdate.class.getName()).log(Level.SEVERE, null, ex);
        }
        loadCombo();

    }

    public void loadCombo() {
        ResultSet rs = v.getTable("SELECT DISTINCT(`ItemName`) FROM `item`");
        item.removeAllItems();
        try {
            while (rs.next()) {

                item.addItem(rs.getString(1));
                item1.addItem(rs.getString(1));
                uname.addItem(rs.getString(1));
                name.addItem(rs.getString(1));
               
            }
            item.setSelectedIndex(-1);

        } catch (SQLException ex) {
            Logger.getLogger(sales.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            ResultSet rs1 = v.getTable("SELECT count(`ItemID`) FROM `item`");
            rs1.next();
            int id = rs1.getInt(1) + 1;
            itid.setText(String.valueOf(id));
        } catch (SQLException ex) {
            Logger.getLogger(StockUpdate.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    view v = new view();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        invo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        item = new javax.swing.JComboBox();
        brand = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        code = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        qty = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        totable = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        home = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        pri = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        su = new javax.swing.JComboBox();
        total = new javax.swing.JTextField();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        jLabel22 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        item1 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        brand1 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        code1 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        qty1 = new javax.swing.JFormattedTextField();
        totable1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        home1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel44 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        dateChooserCombo2 = new datechooser.beans.DateChooserCombo();
        jLabel26 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        up = new javax.swing.JTextField();
        itcode = new javax.swing.JTextField();
        itbrnd = new javax.swing.JTextField();
        itnm = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        itid = new javax.swing.JTextField();
        sup = new javax.swing.JComboBox<String>();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        rbrand = new javax.swing.JComboBox();
        rcode = new javax.swing.JComboBox();
        jLabel34 = new javax.swing.JLabel();
        name = new javax.swing.JComboBox();
        jLabel29 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        uup = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        sup1 = new javax.swing.JComboBox<String>();
        jLabel25 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        uitbrnd = new javax.swing.JComboBox();
        uitcode = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        uname = new javax.swing.JComboBox();
        jLabel35 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        home2 = new javax.swing.JButton();
        jLabel54 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        home3 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton11 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jButton17 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1205, 843));
        getContentPane().setLayout(null);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jTabbedPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabbedPane1FocusGained(evt);
            }
        });
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTabbedPane1MousePressed(evt);
            }
        });

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Invoice No :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(210, 230, 120, 24);

        invo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoActionPerformed(evt);
            }
        });
        jPanel1.add(invo);
        invo.setBounds(320, 230, 100, 30);

        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Date :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(260, 170, 70, 30);

        item.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                itemItemStateChanged(evt);
            }
        });
        item.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                itemMousePressed(evt);
            }
        });
        item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemActionPerformed(evt);
            }
        });
        jPanel1.add(item);
        item.setBounds(710, 170, 123, 30);

        brand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandActionPerformed(evt);
            }
        });
        jPanel1.add(brand);
        brand.setBounds(710, 220, 120, 30);

        jLabel3.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Item :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(650, 170, 90, 24);

        jLabel4.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Item Brand :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(590, 220, 110, 24);

        jPanel1.add(code);
        code.setBounds(980, 170, 115, 30);

        jLabel5.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Item Model :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(860, 170, 110, 24);

        qty.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyActionPerformed(evt);
            }
        });
        qty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                qtyKeyPressed(evt);
            }
        });
        jPanel1.add(qty);
        qty.setBounds(980, 220, 61, 30);

        jLabel8.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Qty :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(930, 220, 70, 24);

        totable.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        totable.setText("ADD");
        totable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totableActionPerformed(evt);
            }
        });
        jPanel1.add(totable);
        totable.setBounds(943, 300, 100, 40);

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Id", "Item Name", "Price(Rs)", "Qty", "Total(Rs)"
            }
        ));
        jScrollPane1.setViewportView(tbl);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(100, 370, 970, 241);

        jButton3.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jButton3.setText("Save");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(960, 700, 110, 47);

        jButton2.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jButton2.setText("Clear");
        jButton2.setPreferredSize(new java.awt.Dimension(127, 27));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(763, 700, 130, 47);

        jButton4.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jButton4.setText("Delete");
        jButton4.setPreferredSize(new java.awt.Dimension(127, 27));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(573, 700, 130, 47);

        jLabel32.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Price : Rs");
        jPanel1.add(jLabel32);
        jLabel32.setBounds(620, 280, 90, 24);

        home.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        home.setText("Home");
        home.setPreferredSize(new java.awt.Dimension(127, 27));
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        jPanel1.add(home);
        home.setBounds(313, 700, 130, 47);

        jLabel6.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Supplier :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(231, 290, 80, 24);

        pri.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                priKeyPressed(evt);
            }
        });
        jPanel1.add(pri);
        pri.setBounds(710, 280, 110, 30);

        jLabel31.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(240, 240, 240));
        jLabel31.setText("Total: Rs");
        jPanel1.add(jLabel31);
        jLabel31.setBounds(840, 620, 80, 50);

        jPanel1.add(su);
        su.setBounds(320, 290, 160, 30);

        total.setEditable(false);
        jPanel1.add(total);
        total.setBounds(920, 630, 160, 30);

        dateChooserCombo1.setCalendarPreferredSize(new java.awt.Dimension(500, 300));
        jPanel1.add(dateChooserCombo1);
        dateChooserCombo1.setBounds(320, 170, 240, 40);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sariya1200.jpg"))); // NOI18N
        jPanel1.add(jLabel22);
        jLabel22.setBounds(0, 0, 1200, 800);

        jTabbedPane1.addTab("Update Stock", jPanel1);

        jPanel2.setMinimumSize(new java.awt.Dimension(1205, 843));
        jPanel2.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Date :");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(190, 190, 70, 60);

        jLabel9.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Item :");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(190, 240, 60, 60);

        item1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                item1ItemStateChanged(evt);
            }
        });
        item1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                item1MousePressed(evt);
            }
        });
        item1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item1ActionPerformed(evt);
            }
        });
        jPanel2.add(item1);
        item1.setBounds(250, 260, 110, 30);

        jLabel10.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("Item Brand :");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(130, 310, 105, 20);

        brand1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brand1ActionPerformed(evt);
            }
        });
        jPanel2.add(brand1);
        brand1.setBounds(250, 310, 110, 30);

        jLabel11.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(240, 240, 240));
        jLabel11.setText("Item Model :");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(460, 250, 110, 40);

        jPanel2.add(code1);
        code1.setBounds(580, 260, 110, 30);

        jLabel12.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(240, 240, 240));
        jLabel12.setText("Qty:");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(530, 310, 40, 20);

        qty1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        qty1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qty1ActionPerformed(evt);
            }
        });
        qty1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                qty1KeyPressed(evt);
            }
        });
        jPanel2.add(qty1);
        qty1.setBounds(580, 310, 70, 30);

        totable1.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        totable1.setText("ADD");
        totable1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totable1ActionPerformed(evt);
            }
        });
        jPanel2.add(totable1);
        totable1.setBounds(900, 310, 83, 40);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Brand", "Model", "Qty", "Reason"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(60, 370, 1030, 290);

        home1.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        home1.setText("Home");
        home1.setPreferredSize(new java.awt.Dimension(127, 27));
        home1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home1ActionPerformed(evt);
            }
        });
        jPanel2.add(home1);
        home1.setBounds(110, 680, 113, 47);

        jButton5.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jButton5.setText("Delete");
        jButton5.setPreferredSize(new java.awt.Dimension(127, 27));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(610, 680, 113, 47);

        jButton6.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jButton6.setText("Clear");
        jButton6.setPreferredSize(new java.awt.Dimension(127, 27));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(760, 680, 113, 47);

        jButton7.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jButton7.setText("Remove");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7);
        jButton7.setBounds(910, 680, 101, 47);

        jLabel44.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(240, 240, 240));
        jLabel44.setText("Reason :");
        jPanel2.add(jLabel44);
        jLabel44.setBounds(500, 194, 80, 40);
        jPanel2.add(jTextField1);
        jTextField1.setBounds(580, 200, 250, 30);

        dateChooserCombo2.setCalendarPreferredSize(new java.awt.Dimension(500, 300));
        jPanel2.add(dateChooserCombo2);
        dateChooserCombo2.setBounds(250, 200, 200, 40);

        jLabel26.setForeground(new java.awt.Color(240, 240, 240));
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sariya1200.jpg"))); // NOI18N
        jPanel2.add(jLabel26);
        jLabel26.setBounds(0, 0, 1200, 800);

        jTabbedPane1.addTab("Remove Items", jPanel2);

        jPanel3.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Item", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(108, 108, 108))); // NOI18N
        jPanel4.setLayout(null);

        up.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel4.add(up);
        up.setBounds(180, 340, 119, 30);

        itcode.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel4.add(itcode);
        itcode.setBounds(180, 245, 119, 30);

        itbrnd.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel4.add(itbrnd);
        itbrnd.setBounds(180, 205, 119, 30);

        itnm.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel4.add(itnm);
        itnm.setBounds(180, 160, 119, 30);

        jLabel13.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(240, 240, 240));
        jLabel13.setText("Item Name:");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(70, 170, 99, 24);

        jLabel14.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(240, 240, 240));
        jLabel14.setText("Item Brand:");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(70, 210, 110, 24);

        jLabel15.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(240, 240, 240));
        jLabel15.setText("Item Model:");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(70, 250, 110, 24);

        jLabel16.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(240, 240, 240));
        jLabel16.setText("Unit Price:");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(80, 340, 88, 24);

        jButton1.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(190, 410, 94, 40);

        jLabel17.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(240, 240, 240));
        jLabel17.setText("Supplier:");
        jPanel4.add(jLabel17);
        jLabel17.setBounds(100, 290, 90, 30);

        jLabel33.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(240, 240, 240));
        jLabel33.setText("Item ID:");
        jPanel4.add(jLabel33);
        jLabel33.setBounds(100, 110, 70, 24);

        itid.setEditable(false);
        itid.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel4.add(itid);
        itid.setBounds(180, 110, 119, 30);

        jPanel4.add(sup);
        sup.setBounds(180, 290, 120, 30);

        jLabel48.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(240, 240, 240));
        jLabel48.setText("Insert item");
        jPanel4.add(jLabel48);
        jLabel48.setBounds(150, 40, 160, 30);

        jLabel49.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(240, 240, 240));
        jLabel49.setText("Insert item");
        jPanel4.add(jLabel49);
        jLabel49.setBounds(150, 40, 160, 30);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sariya1200.jpg"))); // NOI18N
        jPanel4.add(jLabel28);
        jLabel28.setBounds(-10, -10, 420, 530);

        jLabel50.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(240, 240, 240));
        jLabel50.setText("Insert item");
        jPanel4.add(jLabel50);
        jLabel50.setBounds(150, 40, 160, 30);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(70, 170, 370, 490);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Remove Item", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel5.setLayout(null);

        jLabel18.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(240, 240, 240));
        jLabel18.setText("Item Brand:");
        jPanel5.add(jLabel18);
        jLabel18.setBounds(30, 100, 110, 24);

        jLabel19.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(240, 240, 240));
        jLabel19.setText("Item Model:");
        jPanel5.add(jLabel19);
        jLabel19.setBounds(30, 140, 110, 24);

        jButton8.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jButton8.setText("Remove");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton8);
        jButton8.setBounds(114, 200, 120, 40);

        rbrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbrandActionPerformed(evt);
            }
        });
        jPanel5.add(rbrand);
        rbrand.setBounds(140, 100, 119, 30);

        jPanel5.add(rcode);
        rcode.setBounds(140, 140, 119, 30);

        jLabel34.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(240, 240, 240));
        jLabel34.setText("Item Name:");
        jPanel5.add(jLabel34);
        jLabel34.setBounds(30, 60, 110, 24);

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel5.add(name);
        name.setBounds(140, 60, 119, 30);

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sariya1200.jpg"))); // NOI18N
        jPanel5.add(jLabel29);
        jLabel29.setBounds(-50, -10, 380, 490);

        jPanel3.add(jPanel5);
        jPanel5.setBounds(850, 240, 320, 466);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Edit Item", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(108, 108, 108))); // NOI18N
        jPanel6.setLayout(null);

        uup.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPanel6.add(uup);
        uup.setBounds(160, 170, 119, 30);

        jLabel23.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(240, 240, 240));
        jLabel23.setText("Item Brand:");
        jPanel6.add(jLabel23);
        jLabel23.setBounds(50, 54, 120, 30);

        jLabel24.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(240, 240, 240));
        jLabel24.setText("Item Model:");
        jPanel6.add(jLabel24);
        jLabel24.setBounds(50, 94, 130, 30);

        jPanel6.add(sup1);
        sup1.setBounds(160, 130, 120, 30);

        jLabel25.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(240, 240, 240));
        jLabel25.setText("Unit Price:");
        jPanel6.add(jLabel25);
        jLabel25.setBounds(60, 170, 120, 24);

        jButton9.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jButton9.setText("Update");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton9);
        jButton9.setBounds(170, 230, 94, 40);

        uitbrnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uitbrndActionPerformed(evt);
            }
        });
        jPanel6.add(uitbrnd);
        uitbrnd.setBounds(160, 50, 118, 30);

        uitcode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                uitcodeMouseClicked(evt);
            }
        });
        uitcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uitcodeActionPerformed(evt);
            }
        });
        jPanel6.add(uitcode);
        uitcode.setBounds(160, 90, 120, 30);

        jLabel20.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(240, 240, 240));
        jLabel20.setText("Supplier:");
        jPanel6.add(jLabel20);
        jLabel20.setBounds(80, 124, 100, 40);

        uname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                unameMousePressed(evt);
            }
        });
        uname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameActionPerformed(evt);
            }
        });
        jPanel6.add(uname);
        uname.setBounds(160, 10, 119, 30);

        jLabel35.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(240, 240, 240));
        jLabel35.setText("Item Name:");
        jPanel6.add(jLabel35);
        jLabel35.setBounds(40, 10, 110, 30);

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sariya1200.jpg"))); // NOI18N
        jPanel6.add(jLabel30);
        jLabel30.setBounds(-10, -20, 440, 400);

        jPanel3.add(jPanel6);
        jPanel6.setBounds(450, 310, 370, 340);

        home2.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        home2.setText("Home");
        home2.setPreferredSize(new java.awt.Dimension(127, 27));
        home2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home2ActionPerformed(evt);
            }
        });
        jPanel3.add(home2);
        home2.setBounds(90, 690, 113, 47);

        jLabel54.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(240, 240, 240));
        jLabel54.setText("Remove item");
        jPanel3.add(jLabel54);
        jLabel54.setBounds(950, 190, 160, 30);

        jLabel47.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(240, 240, 240));
        jLabel47.setText("Update price");
        jPanel3.add(jLabel47);
        jLabel47.setBounds(550, 250, 160, 30);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sariya1200.jpg"))); // NOI18N
        jPanel3.add(jLabel27);
        jLabel27.setBounds(0, 0, 1200, 800);

        jLabel51.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(240, 240, 240));
        jLabel51.setText("Update price");
        jPanel3.add(jLabel51);
        jLabel51.setBounds(560, 240, 160, 30);

        jLabel52.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(240, 240, 240));
        jLabel52.setText("Update price");
        jPanel3.add(jLabel52);
        jLabel52.setBounds(550, 240, 160, 30);

        jLabel53.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(240, 240, 240));
        jLabel53.setText("Update price");
        jPanel3.add(jLabel53);
        jLabel53.setBounds(560, 240, 160, 30);

        jTabbedPane1.addTab("Settings", jPanel3);

        jPanel7.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Item Name", "Qty"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jPanel7.add(jScrollPane3);
        jScrollPane3.setBounds(40, 150, 1120, 440);

        home3.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        home3.setText("Home");
        home3.setPreferredSize(new java.awt.Dimension(127, 27));
        home3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home3ActionPerformed(evt);
            }
        });
        jPanel7.add(home3);
        home3.setBounds(50, 660, 113, 47);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sariya1200.jpg"))); // NOI18N
        jPanel7.add(jLabel21);
        jLabel21.setBounds(0, 0, 1200, 800);

        jTabbedPane1.addTab("Current Stock", jPanel7);

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3), "Re-Order Level Reached Items", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel13.setMinimumSize(new java.awt.Dimension(1205, 843));
        jPanel13.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel13FocusGained(evt);
            }
        });
        jPanel13.setLayout(null);

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Items", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel15.setForeground(new java.awt.Color(204, 204, 204));
        jPanel15.setLayout(null);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Item Name", "Quantity"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable3);

        jPanel15.add(jScrollPane4);
        jScrollPane4.setBounds(18, 30, 430, 300);

        jPanel13.add(jPanel15);
        jPanel15.setBounds(60, 150, 470, 360);

        jButton11.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jButton11.setText("Send Mail");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton11);
        jButton11.setBounds(790, 640, 117, 46);

        jLabel36.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(240, 240, 240));
        jLabel36.setText("Item ID:");
        jPanel13.add(jLabel36);
        jLabel36.setBounds(760, 540, 100, 30);

        jButton10.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jButton10.setText("Home");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton10);
        jButton10.setBounds(120, 650, 92, 46);
        jPanel13.add(jTextField4);
        jTextField4.setBounds(840, 540, 200, 30);
        jPanel13.add(jTextField5);
        jTextField5.setBounds(840, 580, 100, 30);

        jLabel37.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(240, 240, 240));
        jLabel37.setText("Qty:");
        jPanel13.add(jLabel37);
        jLabel37.setBounds(790, 580, 50, 30);

        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Items to Order", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel16.setForeground(new java.awt.Color(204, 204, 204));
        jPanel16.setLayout(null);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Item Name", "Supplier Email", "Quantity"
            }
        ));
        jScrollPane6.setViewportView(jTable5);

        jPanel16.add(jScrollPane6);
        jScrollPane6.setBounds(20, 30, 430, 300);

        jPanel13.add(jPanel16);
        jPanel16.setBounds(670, 150, 470, 360);

        jButton17.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jButton17.setText("ADD");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton17);
        jButton17.setBounds(980, 580, 80, 40);

        jButton12.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jButton12.setText("Exit");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton12);
        jButton12.setBounds(260, 650, 92, 46);

        jButton18.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jButton18.setText("Clear");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton18);
        jButton18.setBounds(400, 650, 92, 46);

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sariya1200.jpg"))); // NOI18N
        jPanel13.add(jLabel38);
        jLabel38.setBounds(0, 0, 1210, 810);

        jTabbedPane1.addTab("Reorder Items", jPanel13);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 1210, 840);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void invoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_invoActionPerformed

    private void itemItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_itemItemStateChanged
        brand.removeAllItems();
        code.removeAllItems();
        if (!(item.getSelectedIndex() == -1)) {
            String mat = item.getSelectedItem().toString();
            try {
                ResultSet rs1 = v.getTable("SELECT DISTINCT(`Brand`) FROM `item` WHERE ItemName='" + mat + "'");
                ResultSet rs2 = v.getTable("SELECT DISTINCT(`Model`) FROM `item` WHERE ItemName='" + mat + "'");
                while (rs1.next()) {
                    brand.addItem(rs1.getString(1));
                }
                while (rs2.next()) {
                    code.addItem(rs2.getString(1));
                }
                brand.setSelectedIndex(-1);
                code.setSelectedIndex(-1);
            } catch (SQLException ex) {
                Logger.getLogger(sales.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_itemItemStateChanged

    private void itemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemMousePressed

        brand.removeAllItems();
        code.removeAllItems();
        if (!(item.getSelectedIndex() == -1)) {
            String mat = item.getSelectedItem().toString();
            try {
                ResultSet rs1 = v.getTable("SELECT DISTINCT(`Brand`) FROM `item` WHERE ItemName='" + mat + "'");
                ResultSet rs2 = v.getTable("SELECT DISTINCT(`Model`) FROM `item` WHERE ItemName='" + mat + "'");
                while (rs1.next()) {
                    brand.addItem(rs1.getString(1));
                }
                while (rs2.next()) {
                    code.addItem(rs2.getString(1));
                }
                brand.setSelectedIndex(-1);
                code.setSelectedIndex(-1);
            } catch (SQLException ex) {
                Logger.getLogger(sales.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_itemMousePressed

    private void itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemActionPerformed

    }//GEN-LAST:event_itemActionPerformed

    private void qtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyActionPerformed

        String Brand = brand.getSelectedItem().toString();
        String model = code.getSelectedItem().toString();
        int Qty = Integer.valueOf(qty.getText());
        double price = 0;

        if (!(qty.getText().equals("") || Brand.equals("") || model.equals(""))) {
            if (v.check("SELECT `totalstock` FROM `item` WHERE Brand='" + Brand + "' && Model='" + model + "'", Qty)) {
                ResultSet rs = v.getTable("SELECT `price` FROM `item` WHERE Brand='" + Brand + "' && Model='" + model + "'");
                try {

                    while (rs.next()) {
                        price = rs.getDouble(1);
                    }
                    double total1 = Qty * price;
                    DefaultTableModel model1 = (DefaultTableModel) tbl.getModel();
                    model1.addRow(new Object[]{Brand + " " + model, Qty, price, total1});
                    double ttal = 0.0;
                    for (int i = 0; i < model1.getRowCount(); i++) {
                        ttal = ttal + Double.valueOf(model1.getValueAt(i, 4).toString());

                    }
                    total.setText(String.valueOf(ttal));

                } catch (SQLException ex) {
                    Logger.getLogger(sales.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else {
                JOptionPane.showMessageDialog(null, "Product Out of Stock!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Pls fill the relevant fields!");
        }

        item.setSelectedIndex(-1);
        brand.setSelectedIndex(-1);
        code.setSelectedIndex(-1);
        qty.setText("");
    }//GEN-LAST:event_qtyActionPerformed

    private void totableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totableActionPerformed
        // TODO add your handling code here:

        String Brand = brand.getSelectedItem().toString();
        String model = code.getSelectedItem().toString();
        int Qty = Integer.valueOf(qty.getText());
        String price = pri.getText();

        ResultSet rs = v.getTable("SELECT `ItemID` FROM `item` WHERE `Brand`='" + Brand + "' AND `Model`='" + model + "'");
        if (!(qty.getText().equals("") || Brand.equals("") || model.equals("") || pri.getText().equals(""))) {

            try {
                double total1 = Qty * Double.parseDouble(price);
                DefaultTableModel model1 = (DefaultTableModel) tbl.getModel();
                rs.next();
                model1.addRow(new Object[]{rs.getString(1), Brand + " " + model, price, Qty, total1});

                double ttal = 0.0;
                for (int i = 0; i < model1.getRowCount(); i++) {
                    ttal = ttal + Double.valueOf(model1.getValueAt(i, 4).toString());

                }
                total.setText(String.valueOf(ttal));

            } catch (SQLException ex) {
                Logger.getLogger(StockUpdate.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Pls fill the relevant fields!");
        }

        item.setSelectedIndex(-1);
        brand.setSelectedIndex(-1);
        code.setSelectedIndex(-1);
        qty.setText("");
        pri.setText("");
    }//GEN-LAST:event_totableActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        DefaultTableModel mdl = (DefaultTableModel) tbl.getModel();
        if (!(invo.getText().equals("") || su.equals("") || total.equals(""))) {
            String dt = new SimpleDateFormat("yyyy-MM-dd").format(Calendar.getInstance().getTime());
            v.insert("INSERT INTO `iteminvoice`(`date`, `InvoiceNo`, `Total`) VALUES ('" + dt + "','" + invo.getText() + "','" + total.getText() + "')");
            for (int i = 0; i < tbl.getRowCount(); i++) {
                v.insert("INSERT INTO `contain`(`ItemID`, `InvoiceNo`, `Qty`, `price`) VALUES ('" + mdl.getValueAt(i, 0) + "','" + invo.getText() + "','" + mdl.getValueAt(i, 3) + "','" + mdl.getValueAt(i, 2) + "')");
                v.insert("UPDATE `item` SET `TotalStock`=(TotalStock+" + mdl.getValueAt(i, 3) + ") WHERE item.ItemID='" + mdl.getValueAt(i, 0) + "'");

                JOptionPane.showMessageDialog(null, "Done!");
                su.setSelectedIndex(-1);
                invo.setText("");
                total.setText("");

                mdl.setRowCount(0);

            }
        } else {
            JOptionPane.showMessageDialog(null, "Pls fill the relevant fields!");
        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel mdl = (DefaultTableModel) tbl.getModel();
        mdl.setRowCount(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel mdl = (DefaultTableModel) tbl.getModel();
        mdl.removeRow(tbl.getSelectedRow());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        this.dispose();
        DashBoard dbd = new DashBoard();
        dbd.setVisible(true);
    }//GEN-LAST:event_homeActionPerformed

    private void item1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_item1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_item1ItemStateChanged

    private void item1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_item1MousePressed
        brand1.removeAllItems();
        code1.removeAllItems();
        if (!(item1.getSelectedIndex() == -1)) {
            String mat = item1.getSelectedItem().toString();
            try {
                ResultSet rs1 = v.getTable("SELECT DISTINCT(`Brand`) FROM `item` WHERE ItemName='" + mat + "'");
                ResultSet rs2 = v.getTable("SELECT DISTINCT(`Model`) FROM `item` WHERE ItemName='" + mat + "'");
                while (rs1.next()) {
                    brand1.addItem(rs1.getString(1));
                }
                while (rs2.next()) {
                    code1.addItem(rs2.getString(1));
                }
                brand1.setSelectedIndex(-1);
                code1.setSelectedIndex(-1);
            } catch (SQLException ex) {
                Logger.getLogger(sales.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_item1MousePressed

    private void item1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item1ActionPerformed

    private void qty1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qty1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qty1ActionPerformed

    int count = 0;
    private void totable1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totable1ActionPerformed
        String Brand = brand1.getSelectedItem().toString();
        String model = code1.getSelectedItem().toString();
        int Qty = Integer.valueOf(qty1.getText());
        String reason = jTextField1.getText();
        ResultSet rs = v.getTable("SELECT `ItemID` FROM `item` WHERE `Brand`='" + Brand + "' AND `Model`='" + model + "'");
        if (!(qty1.getText().equals("") || Brand.equals("") || model.equals(""))) {

            try {

                DefaultTableModel model1 = (DefaultTableModel) jTable2.getModel();
                rs.next();
                model1.addRow(new Object[]{rs.getString(1), Brand, model, Qty, reason});
                count++;
                item1.setSelectedIndex(-1);
                brand1.setSelectedIndex(-1);
                code1.setSelectedIndex(-1);
                qty1.setText("");
                jTextField1.setText("");
            } catch (SQLException ex) {
                Logger.getLogger(StockUpdate.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Pls fill the relevant fields!");
        }


    }//GEN-LAST:event_totable1ActionPerformed

    private void home1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home1ActionPerformed
        DashBoard d = new DashBoard();
        d.setVisible(true);
        this.setVisible(false);


    }//GEN-LAST:event_home1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        DefaultTableModel model1 = (DefaultTableModel) jTable2.getModel();

        model1.removeRow(jTable2.getSelectedRow());
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        DefaultTableModel model1 = (DefaultTableModel) jTable2.getModel();
        model1.setRowCount(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        String today = new SimpleDateFormat("yyyy-MM-dd").format(Calendar.getInstance().getTime());
        if (count != 0) {

            for (int i = 0; i < jTable2.getRowCount(); i++) {
                try {
                    String rea = jTable2.getValueAt(i, 4).toString();
                    if (rea.equals("")) {
                        rea = "-";
                    }
                    PreparedStatement ps = DBconnection.DB.mycon().prepareStatement("insert into removed values('" + jTable2.getValueAt(i, 0).toString() + "','" + jTable2.getValueAt(i, 3).toString() + "','" + today + "' ,'" + rea + "') ");
                    ps.execute();

                    v.insert("update item set TotalStock=(TotalStock-" + Integer.parseInt(jTable2.getValueAt(i, 3).toString()) + ") where ItemID='" + jTable2.getValueAt(i, 0).toString() + "'");

                    JOptionPane.showMessageDialog(null, "Done!");
                    DefaultTableModel model1 = (DefaultTableModel) jTable2.getModel();
                    model1.setRowCount(0);
                } catch (SQLException ex) {
                    Logger.getLogger(StockUpdate.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }


    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (itid.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Item Id can not be empty");
        } else if (itnm.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Item name can not be empty");
        } else if (itcode.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Item Model can not be empty");
        } else if (itbrnd.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Item Brand can not be empty");
        } else if (sup.getSelectedItem().equals("")) {
            JOptionPane.showMessageDialog(null, "Supplier Id is not selected");
        } else if (up.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Unit price can not be empty");
        } else {
            String[] s = sup.getSelectedItem().toString().split(" ");
            v.insert("INSERT INTO item values('" + itid.getText() + "','" + itnm.getText() + "','" + itbrnd.getText() + "','" + itcode.getText() + "','" + up.getText() + "','" + s[0] + "','0')");
            JOptionPane.showMessageDialog(null, "New Product successfully added!");
            itid.setText("");
            itnm.setText("");
            itcode.setText("");
            itbrnd.setText("");
            sup.setSelectedItem("");
            up.setText("");
            loadCombo();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void home2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home2ActionPerformed

        this.dispose();
        DashBoard dbd = new DashBoard();
        dbd.setVisible(true);
    }//GEN-LAST:event_home2ActionPerformed

    private void home3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home3ActionPerformed
        this.dispose();
        DashBoard dbd = new DashBoard();
        dbd.setVisible(true);
    }//GEN-LAST:event_home3ActionPerformed

    private void unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameActionPerformed

        

        ResultSet rs = v.getTable("select Brand from item where ItemName='" + uname.getSelectedItem() + "'");
        try {
            while (rs.next()) {
                uitbrnd.addItem(rs.getString(1));

            }
        } catch (SQLException ex) {
            Logger.getLogger(StockUpdate.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_unameActionPerformed

    private void uitbrndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uitbrndActionPerformed
        ResultSet rs = v.getTable("select Model from item where Brand='" + uitbrnd.getSelectedItem() + "'");
        uitcode.removeAllItems();
        try {
            while (rs.next()) {
                uitcode.addItem(rs.getString(1));

            }
        } catch (SQLException ex) {
            Logger.getLogger(StockUpdate.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_uitbrndActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed

        ResultSet rs = v.getTable("select Brand from item where ItemName='" + name.getSelectedItem() + "'");
        try {
            rbrand.removeAllItems();
            while (rs.next()) {
                rbrand.addItem(rs.getString(1));

            }
        } catch (SQLException ex) {
            Logger.getLogger(StockUpdate.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_nameActionPerformed

    private void rbrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbrandActionPerformed
        ResultSet rs = v.getTable("select Model from item where Brand='" + rbrand.getSelectedItem() + "'");
        try {
            while (rs.next()) {
                rcode.addItem(rs.getString(1));

            }
        } catch (SQLException ex) {
            Logger.getLogger(StockUpdate.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rbrandActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if (uup.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Pls enter the Unit price");
        } else {
            v.update("update item set Price='" + uup.getText() + "' where Brand='" + uitbrnd.getSelectedItem() + "' && Model='" + uitcode.getSelectedItem() + "'");

            JOptionPane.showMessageDialog(null, "Update successful");
            loadCombo();
            uitbrnd.setSelectedIndex(-1);

        }


    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if (name.getSelectedItem().equals("")) {
            JOptionPane.showMessageDialog(null, "Pls select the item first");
        } else {
            v.delete("DELETE FROM `item` WHERE Brand='" + rbrand.getSelectedItem() + "' && Model='" + rcode.getSelectedItem() + "' ");
            JOptionPane.showMessageDialog(null, "Item deleted successfully");
            loadCombo();
            name.setSelectedIndex(-1);
        }


    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        String today = new SimpleDateFormat("yyyy-MM-dd").format(Calendar.getInstance().getTime());

        JFileChooser dialog = new JFileChooser();
        dialog.setSelectedFile(new File("ReOrder Report " + today + ".pdf"));
        int dialogResult = dialog.showSaveDialog(null);
        if (dialogResult == JFileChooser.APPROVE_OPTION) {
            String filePath = dialog.getSelectedFile().getPath();
            Document document = new Document(PageSize.A4, 50, 50, 140, 140);

            //Creation of PdfWriter object
            try {

                PdfWriter writer = PdfWriter.getInstance(document,
                        new FileOutputStream(filePath));
                document.open();
                // writer.setPageEvent(new MyPdfPageEventHelper("Service.png"));
            } catch (Exception e) {
                System.out.println(e);
            }

            Paragraph title2 = new Paragraph("Re-Order Report",
                    FontFactory.getFont(FontFactory.HELVETICA,
                            18, Font.ITALIC, new CMYKColor(75, 68, 67, 90)));
            Chapter chapter2 = new Chapter(title2, 1);
            Paragraph title = new Paragraph("Date : " + today,
                    FontFactory.getFont(FontFactory.TIMES_ROMAN,
                            14, Font.NORMAL, new CMYKColor(75, 68, 67, 90)));

            try {
                title2.setAlignment(Element.ALIGN_CENTER);
                document.add(title2);

                PdfPTable t = new PdfPTable(2);
                t.setSpacingBefore(5);
                t.setSpacingAfter(5);

                PdfPTable t1 = new PdfPTable(2);
                t1.setSpacingBefore(5);
                t1.setSpacingAfter(5);

                //chapter1.setNumberDepth(0);
                document.add(title);

                //t1.addCell("ItemNo");
                t.addCell("Item Name");
                t.addCell("Amount");

                for (int i = 0; i < jTable5.getRowCount(); i++) {
                    String ItemName = jTable5.getValueAt(i, 1).toString();
                    String amnt = jTable5.getValueAt(i, 2).toString();

                    //t1.addCell(orderID);
                    t.addCell(ItemName);
                    t.addCell(amnt);

                }

                document.add(Chunk.NEWLINE);

                document.add(t);

                document.add(Chunk.NEWLINE);

                document.add(Chunk.NEWLINE);
                document.add(t1);
                document.close();
                Email e = new Email();
                e.send2(filePath, "ReOrder Report-" + today);
                System.out.println(document);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }


    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        DashBoard dbd = new DashBoard();
        dbd.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed
    int count1 = 0;
    private void jTabbedPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane1FocusGained
//
//        //reorder table filling
//        ResultSet rs2=v.getTable("select*from item");
//        DefaultTableModel tb2 = (DefaultTableModel) jTable3.getModel();
//        try {
//            while(rs2.next()){
//                
//                tb2.addRow(new Object[]{rs2.getString(1), rs2.getString(2)+ rs2.getString(7)});
//                
//            }
//        } catch (SQLException ex) {
//            Logger.getLogger(StockUpdate.class.getName()).log(Level.SEVERE, null, ex);
//        }

//        try {
//            ResultSet rs = v.getTable("SELECT `ItemID`, `ItemName`, `Brand`, `Model`, `TotalStock` FROM `item` ORDER BY ItemID ASC");
//            DefaultTableModel tb = (DefaultTableModel) jTable1.getModel();
//            jTable1.removeAll();
//            while (rs.next()) {
//                tb.addRow(new Object[]{rs.getString(1), rs.getString(2) + " " + rs.getString(3) + " " + rs.getString(4), rs.getString(5)});
//            }
//        } catch (SQLException ex) {
//            Logger.getLogger(StockUpdate.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_jTabbedPane1FocusGained

    private void jTabbedPane1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MousePressed
        try {

            ResultSet rs = v.getTable("SELECT `ItemID`, `ItemName`, `Brand`, `Model`, `TotalStock` FROM `item` ORDER BY ItemID ASC");
            DefaultTableModel tb = (DefaultTableModel) jTable1.getModel();
            for (int i = 0; i < tb.getRowCount(); i++) {
                tb.removeRow(i);
            }
            while (rs.next()) {
                tb.addRow(new Object[]{rs.getString(1), rs.getString(2) + " " + rs.getString(3) + " " + rs.getString(4), rs.getString(5)});
            }
        } catch (SQLException ex) {
            Logger.getLogger(StockUpdate.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            jTable3.removeAll();
            ResultSet rs1 = v.getTable("SELECT `ItemID`, `ItemName`, `Brand`, `Model`, `TotalStock` FROM `item` ORDER BY TotalStock ASC");
            DefaultTableModel tb1 = (DefaultTableModel) jTable3.getModel();
            for (int i = 0; i < tb1.getRowCount(); i++) {
                tb1.removeRow(i);
            }
            int x = 15;
            while (rs1.next()) {
                tb1.addRow(new Object[]{rs1.getString(1), rs1.getString(2) + " " + rs1.getString(3) + " " + rs1.getString(4), rs1.getString(5)});

                if (x == 0) {
                    break;
                }
                x--;
            }
        } catch (SQLException ex) {
            Logger.getLogger(StockUpdate.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTabbedPane1MousePressed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        if (!(jTextField4.getText().equals("") || jTextField5.getText().equals(""))) {

            try {
                String item = jTextField4.getText();

                PreparedStatement ps = DBconnection.DB.mycon().prepareStatement("select supplier.Email from supplier inner join item on supplier.SupplierID=item.SupplierID where item.ItemID='" + item + "'");
                ResultSet rs = ps.executeQuery();

                String qty = jTextField5.getText();
                DefaultTableModel tbl1 = (DefaultTableModel) jTable5.getModel();
                TableModel tbl = jTable3.getModel();
                String name = null;
                for (int i = 0; i < tbl.getRowCount(); i++) {
                    if (item.equals(tbl.getValueAt(i, 0))) {
                        name = tbl.getValueAt(i, 1).toString();
                    }
                }
                rs.next();
                tbl1.addRow(new Object[]{item, name, rs.getString(1), qty});
                jTextField4.setText("");
                jTextField5.setText("");
            } catch (SQLException ex) {
                Logger.getLogger(StockUpdate.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Pls fill the relevant fields");
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jPanel13FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel13FocusGained

    }//GEN-LAST:event_jPanel13FocusGained

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void unameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unameMousePressed
        uitbrnd.removeAllItems();
        uitcode.removeAllItems();
        if (!(uname.getSelectedIndex() == -1)) {
            String mat = uname.getSelectedItem().toString();
            try {
                ResultSet rs1 = v.getTable("SELECT DISTINCT(`Brand`) FROM `item` WHERE ItemName='" + mat + "'");
                ResultSet rs2 = v.getTable("SELECT DISTINCT(`Model`) FROM `item` WHERE ItemName='" + mat + "'");
                while (rs1.next()) {
                    uitbrnd.addItem(rs1.getString(1));
                }
                while (rs2.next()) {
                    uitcode.addItem(rs2.getString(1));
                }
                uitbrnd.setSelectedIndex(-1);
                uitcode.setSelectedIndex(-1);
            } catch (SQLException ex) {
                Logger.getLogger(sales.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_unameMousePressed

    private void brand1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brand1ActionPerformed
        ResultSet rs = v.getTable("select Model from item where Brand='" + brand1.getSelectedItem() + "'");
        code1.removeAllItems();
        try {
            while (rs.next()) {
                code1.addItem(rs.getString(1));

            }
        } catch (SQLException ex) {
            Logger.getLogger(StockUpdate.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_brand1ActionPerformed

    private void brandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandActionPerformed
        ResultSet rs = v.getTable("select Model from item where Brand='" + brand.getSelectedItem() + "'");
        code.removeAllItems();
        try {
            while (rs.next()) {
                code.addItem(rs.getString(1));

            }
        } catch (SQLException ex) {
            Logger.getLogger(StockUpdate.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_brandActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        jTextField4.setText(jTable3.getValueAt(jTable3.getSelectedRow(), 0).toString());

    }//GEN-LAST:event_jTable3MouseClicked

    private void priKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priKeyPressed
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            pri.setEditable(true);
        } else {

            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE || evt.getExtendedKeyCode() == KeyEvent.VK_PERIOD) {
                // allo edit
                pri.setEditable(true);
            } else {
                pri.setEditable(false);
            }
        }          // TODO add your handling code here:
    }//GEN-LAST:event_priKeyPressed

    private void qtyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyKeyPressed
        String ph = qty.getText();

        int len = ph.length();
        char c = evt.getKeyChar();
        // check the character
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {

            if (len < 3) {
                qty.setEditable(true);
            } else {
                qty.setEditable(false);

            }
        } else {
            //erase number 'backspace work'
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
                // allo edit
                qty.setEditable(true);
            } else {
                qty.setEditable(false);
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_qtyKeyPressed

    private void qty1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qty1KeyPressed
        String ph = qty1.getText();

        int len = ph.length();
        char c = evt.getKeyChar();
        // check the character
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {

            if (len < 3) {
                qty1.setEditable(true);
            } else {
                qty1.setEditable(false);

            }
        } else {
            //erase number 'backspace work'
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
                // allo edit
                qty1.setEditable(true);
            } else {
                qty1.setEditable(false);
            }
        }        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_qty1KeyPressed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        DefaultTableModel mdl = (DefaultTableModel) jTable5.getModel();
        mdl.setRowCount(0);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void uitcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uitcodeActionPerformed
       
    }//GEN-LAST:event_uitcodeActionPerformed

    private void uitcodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uitcodeMouseClicked
        ResultSet rs1 = v.getTable("select supplier.SupplierID from supplier inner join item on supplier.SupplierID=item.SupplierID where item.Brand='" + uitbrnd.getSelectedItem().toString() + "' and item.Model='"+uitcode.getSelectedItem().toString()+"'");
        sup1.removeAllItems();
        try {
            while (rs1.next()) {
                sup1.addItem(rs1.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(StockUpdate.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_uitcodeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StockUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StockUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StockUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StockUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StockUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox brand;
    private javax.swing.JComboBox brand1;
    private javax.swing.JComboBox code;
    private javax.swing.JComboBox code1;
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private datechooser.beans.DateChooserCombo dateChooserCombo2;
    private javax.swing.JButton home;
    private javax.swing.JButton home1;
    private javax.swing.JButton home2;
    private javax.swing.JButton home3;
    private javax.swing.JTextField invo;
    private javax.swing.JTextField itbrnd;
    private javax.swing.JTextField itcode;
    private javax.swing.JComboBox item;
    private javax.swing.JComboBox item1;
    private javax.swing.JTextField itid;
    private javax.swing.JTextField itnm;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JComboBox name;
    private javax.swing.JTextField pri;
    private javax.swing.JFormattedTextField qty;
    private javax.swing.JFormattedTextField qty1;
    private javax.swing.JComboBox rbrand;
    private javax.swing.JComboBox rcode;
    private javax.swing.JComboBox su;
    private javax.swing.JComboBox<String> sup;
    private javax.swing.JComboBox<String> sup1;
    private javax.swing.JTable tbl;
    private javax.swing.JButton totable;
    private javax.swing.JButton totable1;
    private javax.swing.JTextField total;
    private javax.swing.JComboBox uitbrnd;
    private javax.swing.JComboBox uitcode;
    private javax.swing.JComboBox uname;
    private javax.swing.JTextField up;
    private javax.swing.JTextField uup;
    // End of variables declaration//GEN-END:variables
}
