/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ServiceCenter;

import DBconnection.DB;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shehan Atapattu
 */
public class sup extends javax.swing.JFrame {

    /**
     * Creates new form sup
     */
    public sup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        add = new javax.swing.JTextField();
        tel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        sup = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        mail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        upadd = new javax.swing.JTextField();
        uptel = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        upsup = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        upemail = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        upsup1 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N

        jPanel1.setLayout(null);

        jButton1.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jButton1.setText("Save");
        jButton1.setPreferredSize(new java.awt.Dimension(10, 10));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(720, 430, 110, 50);

        jLabel4.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Telephone No :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(300, 240, 140, 40);

        jButton3.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jButton3.setText("Clear");
        jButton3.setPreferredSize(new java.awt.Dimension(10, 10));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(540, 430, 130, 50);

        jLabel5.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("E-mail :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(370, 290, 120, 50);

        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add);
        add.setBounds(450, 200, 410, 30);

        tel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                telKeyPressed(evt);
            }
        });
        jPanel1.add(tel);
        tel.setBounds(450, 250, 410, 30);

        jLabel3.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Address :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(350, 190, 120, 40);
        jPanel1.add(sup);
        sup.setBounds(450, 150, 410, 30);

        jButton2.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jButton2.setText("Home");
        jButton2.setPreferredSize(new java.awt.Dimension(10, 10));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(350, 430, 130, 50);

        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Supplier Name :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(290, 150, 140, 40);
        jPanel1.add(mail);
        mail.setBounds(450, 300, 410, 30);

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sariya1200.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1200, 800);

        jTabbedPane1.addTab("Add supplier", jPanel1);

        jPanel2.setLayout(null);

        jButton4.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jButton4.setText("Save");
        jButton4.setPreferredSize(new java.awt.Dimension(10, 10));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(760, 510, 110, 50);

        jLabel7.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Telephone No :");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(240, 270, 130, 40);

        jButton5.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jButton5.setText("Clear");
        jButton5.setPreferredSize(new java.awt.Dimension(10, 10));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(570, 510, 130, 50);

        jLabel8.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("E-mail :");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(310, 330, 100, 30);

        upadd.setEditable(false);
        jPanel2.add(upadd);
        upadd.setBounds(380, 210, 330, 40);

        uptel.setEditable(false);
        jPanel2.add(uptel);
        uptel.setBounds(380, 270, 330, 40);

        jLabel9.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Address :");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(290, 210, 100, 30);
        jPanel2.add(upsup);
        upsup.setBounds(380, 150, 330, 40);

        jButton6.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jButton6.setText("Home");
        jButton6.setPreferredSize(new java.awt.Dimension(10, 10));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(210, 510, 130, 50);

        jLabel11.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(240, 240, 240));
        jLabel11.setText("Supplier Name :");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(240, 150, 140, 30);

        upemail.setEditable(false);
        jPanel2.add(upemail);
        upemail.setBounds(380, 330, 330, 40);

        jButton7.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jButton7.setText("Search");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7);
        jButton7.setBounds(760, 150, 100, 40);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sariya1200.jpg"))); // NOI18N
        jPanel2.add(jLabel12);
        jLabel12.setBounds(0, 0, 1200, 810);

        jTabbedPane1.addTab("Update supplier", jPanel2);

        jPanel3.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(240, 240, 240));
        jLabel13.setText("Supplier Name :");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(160, 150, 140, 40);
        jPanel3.add(upsup1);
        upsup1.setBounds(310, 150, 330, 40);

        jButton10.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jButton10.setText("Home");
        jButton10.setPreferredSize(new java.awt.Dimension(10, 10));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton10);
        jButton10.setBounds(250, 530, 130, 50);

        jButton9.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jButton9.setText("Remove");
        jButton9.setPreferredSize(new java.awt.Dimension(10, 10));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton9);
        jButton9.setBounds(740, 530, 130, 50);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Address", "Tel", "e-mail"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(112, 230, 890, 200);

        jButton8.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jButton8.setText("Search");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8);
        jButton8.setBounds(760, 150, 100, 40);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sariya1200.jpg"))); // NOI18N
        jPanel3.add(jLabel14);
        jLabel14.setBounds(0, 0, 1200, 790);

        jTabbedPane1.addTab("Remove supplier", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1197, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DashBoard dc = new DashBoard();
        dc.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        DashBoard dc = new DashBoard();
        dc.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        upadd.setEditable(true);
        upemail.setEditable(true);
        uptel.setEditable(true);

        ResultSet rs = v.getTable("SELECT `Address`, `Telephone`, `Email` FROM `supplier` WHERE `Name`='" + upsup.getText() + "' AND `isDeleted`=0");

        try {
            while (rs.next()) {
                upadd.setText(rs.getString(1));
                uptel.setText(rs.getString(2));
                upemail.setText(rs.getString(3));
            }
        } catch (SQLException ex) {
            Logger.getLogger(sup.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (sup.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Pls enter the supplier name");
        } else if (add.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Pls enter the address");
        } else if (tel.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Pls enter the telephone no.");
        } else if (mail.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Pls enter the e-mail address");
        } else {
            v.insert("INSERT INTO `supplier` VALUES ('0','" + sup.getText() + "','" + add.getText() + "','" + tel.getText() + "','" + mail.getText() + "',0)");
            JOptionPane.showMessageDialog(null, "Done!");
            sup.setText("");
            add.setText("");
            tel.setText("");
            mail.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        upsup.setText("");
        upadd.setText("");
        upemail.setText("");
        uptel.setText("");

        upadd.setEditable(false);
        upemail.setEditable(false);
        uptel.setEditable(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        if (sup.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Pls enter the supplier name");
        } else if (add.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Pls enter the address");
        } else if (tel.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Pls enter the telephone no.");
        } else if (mail.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Pls enter the e-mail address");
        } else {
            v.update("UPDATE `supplier` SET `Address`='" + add.getText() + "',`Telephone`='" + tel.getText() + "',`Email`='" + mail.getText() + "' WHERE `Name`='" + sup.getText() + "'");
            JOptionPane.showMessageDialog(null, "Done!");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        sup.setText("");
        add.setText("");
        tel.setText("");
        mail.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String suppliernm = upsup1.getText();
        PreparedStatement ps;
        ResultSet rst;
        try {
            ps = DB.mycon().prepareStatement("SELECT `Name`, `Address`, `Telephone`, `Email` FROM `supplier` WHERE Name='" + suppliernm + "' AND `isDeleted`=0");
            rst = ps.executeQuery();
            DefaultTableModel tb = (DefaultTableModel) jTable1.getModel();
            while (rst.next()) {
                tb.addRow(new Object[]{rst.getString(1), rst.getString(2), rst.getString(3), rst.getString(4)});

            }
            if (tb.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "Supplier not found");
            }
        } catch (SQLException ex) {
            Logger.getLogger(sup.class.getName()).log(Level.SEVERE, null, ex);
        }

        upsup1.setText("");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        PreparedStatement ps;

        try {
            ps = DB.mycon().prepareStatement("UPDATE `supplier` SET `isDeleted`=1 WHERE Name='" + jTable1.getModel().getValueAt(0, 0) + "'");

            int x = JOptionPane.showConfirmDialog(null, "Do you want to continue");
            if (x == JOptionPane.YES_OPTION) {
                ps.execute();
                JOptionPane.showMessageDialog(null, "Done!!");
                jTable1.removeAll();
            }
        } catch (SQLException ex) {
            Logger.getLogger(sup.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        DashBoard dc = new DashBoard();
        dc.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addActionPerformed

    private void telKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telKeyPressed
   String ph=tel.getText();
      
      int len=ph.length();
      char c= evt.getKeyChar();
      // check the character
      if(evt.getKeyChar()>='0'&& evt.getKeyChar()<='9'){
          
      if(len<10){
      tel.setEditable(true);
      }else{
    tel.setEditable(false);
      
      }
      }
      else{
      //erase number 'backspace work'
      if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
          // allo edit
        tel.setEditable(true);
      }else{
           tel.setEditable(false);
      }
      }        // TODO add your handling code here:
    }//GEN-LAST:event_telKeyPressed
    view v = new view();

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField mail;
    private javax.swing.JTextField sup;
    private javax.swing.JTextField tel;
    private javax.swing.JTextField upadd;
    private javax.swing.JTextField upemail;
    private javax.swing.JTextField upsup;
    private javax.swing.JTextField upsup1;
    private javax.swing.JTextField uptel;
    // End of variables declaration//GEN-END:variables
}
